// packages/blade-svelte/src/components/Checkbox/Checkbox.svelte
<script module lang="ts">
  declare const __DEV__: boolean;
</script>

<script lang="ts">
  import { untrack, type Snippet } from 'svelte';
  import {
    metaAttribute,
    MetaConstants,
    makeAccessible,
    makeAnalyticsAttribute,
    getStyledPropsClasses,
  } from '@razorpay/blade-core/utils';
  import {
    getCheckboxTitleClasses,
    getCheckboxSupportClasses,
    getCheckboxSupportTextClasses,
    getCheckboxHintClasses,
    getCheckboxHintWrapperClasses,
    getCheckboxTemplateClasses,
  } from '@razorpay/blade-core/styles';
  import CheckboxIcon from './CheckboxIcon.svelte';
  import { InfoIcon } from '../Icons';
  import { getCheckboxGroupContext } from './checkboxContext';
  import type { CheckboxProps } from './types';

  const templateClasses = getCheckboxTemplateClasses();

  let {
    isChecked,
    defaultChecked,
    onChange,
    children,
    helpText,
    errorText,
    isIndeterminate = false,
    name,
    value,
    isDisabled,
    isRequired,
    validationState,
    size = 'medium',
    tabIndex,
    testID,
    ...rest
  }: CheckboxProps = $props();

  const groupProps = getCheckboxGroupContext();

  if (typeof __DEV__ !== 'undefined' && __DEV__) {
    const hasBannedProp =
      validationState !== undefined ||
      name !== undefined ||
      defaultChecked !== undefined ||
      isChecked !== undefined ||
      onChange !== undefined;
    if (hasBannedProp && groupProps) {
      const bannedProps = [
        validationState !== undefined ? 'validationState' : undefined,
        name !== undefined ? 'name' : undefined,
        defaultChecked !== undefined ? 'defaultChecked' : undefined,
        isChecked !== undefined ? 'isChecked' : undefined,
        onChange !== undefined ? 'onChange' : undefined,
      ]
        .filter(Boolean)
        .join(',');
      // eslint-disable-next-line no-console
      console.error(
        `[Blade Checkbox]: Cannot set \`${bannedProps}\` on <Checkbox /> when it's inside <CheckboxGroup />. Please set it on the <CheckboxGroup /> itself.`,
      );
    }
    if (!value && groupProps) {
      // eslint-disable-next-line no-console
      console.error(
        '[Blade Checkbox]: <CheckboxGroup /> requires that you pass a unique "value" prop to each <Checkbox />.',
      );
    }
  }

  // ── Group context merge (precedence mirrors React Checkbox.tsx) ──
  const _validationState = $derived(validationState ?? groupProps?.validationState);
  const _hasError = $derived(_validationState === 'error');
  const _isDisabled = $derived(isDisabled ?? groupProps?.isDisabled ?? false);
  const _isRequired = $derived(
    Boolean(isRequired || groupProps?.isRequired || groupProps?.necessityIndicator === 'required'),
  );
  const _name = $derived(name ?? groupProps?.name);
  const _size = $derived(groupProps?.size ?? size);

  // ── Controllable checked ──
  // Standalone: `isChecked` (controlled) | internal `$state` seeded by `defaultChecked`.
  // Inside group: group state is the source of truth.
  let internalChecked = $state(untrack(() => defaultChecked) ?? false);

  const isInGroup = $derived(Boolean(groupProps));
  const groupChecked = $derived(value ? groupProps?.state?.isChecked(value) ?? false : false);

  const isControlled = $derived(isInGroup || isChecked !== undefined);
  const isCheckedState = $derived(
    isInGroup ? groupChecked : isChecked !== undefined ? isChecked : internalChecked,
  );

  const showSupportingText = $derived(Boolean(helpText));

  let inputEl: HTMLInputElement | undefined = $state();

  export function focus(options?: FocusOptions): void {
    inputEl?.focus(options);
  }

  // indeterminate is an IDL prop, not an attribute — set it imperatively.
  $effect(() => {
    if (inputEl) {
      inputEl.indeterminate = Boolean(isIndeterminate);
    }
  });

  function handleChange(event: Event): void {
    if (_isDisabled) {
      event.stopPropagation();
      event.preventDefault();
      return;
    }
    const next = !isCheckedState;
    if (isInGroup && value) {
      if (next) {
        groupProps?.state?.addValue(value);
      } else {
        groupProps?.state?.removeValue(value);
      }
    } else if (!isControlled) {
      internalChecked = next;
    }
    onChange?.({ isChecked: next, value, event });
  }

  const isStringChildren = $derived(typeof children === 'string');
  const snippetChildren = $derived(!isStringChildren ? (children as Snippet | undefined) : undefined);
  const hasChildren = $derived(Boolean(children));

  // ── ids ──
  const idBase = `checkbox-${Math.random().toString(36).slice(2, 8)}`;
  const helpTextId = `${idBase}-help`;
  const errorTextId = `${idBase}-error`;

  const titleClasses = $derived(getCheckboxTitleClasses({ size: _size, isDisabled: _isDisabled }));
  const supportClasses = $derived(getCheckboxSupportClasses({ size: _size }));
  const supportTextClasses = $derived(getCheckboxSupportTextClasses({ size: _size }));
  const hintClasses = $derived(
    getCheckboxHintClasses({ size: _size, type: _hasError ? 'error' : 'help' }),
  );
  const hintWrapperClasses = $derived(getCheckboxHintWrapperClasses({ size: _size }));

  const styledProps = $derived(getStyledPropsClasses(rest));
  const wrapperClasses = $derived(
    [templateClasses.checkbox, ...(styledProps.classes || [])].filter(Boolean).join(' '),
  );
  const wrapperStyles = $derived(
    Object.entries(styledProps.inlineStyles || {})
      .map(([prop, val]) => `${prop}: ${val}`)
      .join('; ') || undefined,
  );

  const metaAttrs = $derived(metaAttribute({ name: MetaConstants.Checkbox, testID }));
  const labelMetaAttrs = metaAttribute({ name: MetaConstants.CheckboxLabel });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));

  const a11yAttrs = $derived(
    makeAccessible({
      role: 'checkbox',
      required: _isRequired,
      invalid: _hasError,
      disabled: _isDisabled,
      checked: isIndeterminate ? 'mixed' : isCheckedState,
      ...(_hasError ? { errorMessage: errorTextId } : {}),
      ...(showSupportingText ? { describedBy: helpTextId } : {}),
    }),
  );

  const showFormHint = $derived(_hasError && Boolean(errorText));

  // React FormHint icon sizing: small/medium hint -> 'small', large -> 'medium'.
  const hintIconSize = $derived(_size === 'large' ? 'medium' : 'small');
</script>

<div class={wrapperClasses} style={wrapperStyles} {...metaAttrs}>
  <label class={templateClasses.label} data-disabled={_isDisabled || undefined} {...labelMetaAttrs}>
    <div class={templateClasses.field}>
      <div class={templateClasses.row}>
        <input
          bind:this={inputEl}
          class={templateClasses.input}
          type="checkbox"
          name={_name}
          {value}
          tabindex={tabIndex}
          checked={isCheckedState}
          disabled={_isDisabled || undefined}
          required={_isRequired || undefined}
          onchange={handleChange}
          {...a11yAttrs}
          {...analyticsAttrs}
        />
        <CheckboxIcon
          size={_size}
          isChecked={isCheckedState}
          {isIndeterminate}
          isDisabled={_isDisabled}
          isNegative={_hasError}
        />
        {#if hasChildren}
          <span class={titleClasses}>
            {#if isStringChildren}
              {children}
            {:else if snippetChildren}
              {@render snippetChildren()}
            {/if}
          </span>
        {/if}
      </div>
      {#if showSupportingText}
        <span class={supportClasses} id={helpTextId}>
          <span class={supportTextClasses}>{helpText}</span>
        </span>
      {/if}
    </div>
  </label>
  {#if showFormHint}
    <span class={hintWrapperClasses}>
      <span class={templateClasses.hintIcon}>
        <InfoIcon size={hintIconSize} color="feedback.icon.negative.intense" />
      </span>
      <span class={hintClasses} id={errorTextId}>{errorText}</span>
    </span>
  {/if}
</div>

// packages/blade/src/components/Checkbox/Checkbox.tsx
/* eslint-disable @typescript-eslint/restrict-plus-operands */
/* eslint-disable @typescript-eslint/no-shadow */
import React from 'react';
import { useCheckboxGroupContext } from './CheckboxGroup/CheckboxGroupContext';
import { CheckboxIcon } from './CheckboxIcon';
import { useCheckbox } from './useCheckbox';
import { checkboxHoverTokens, checkboxSizes } from './checkboxTokens';
import isEmpty from '~utils/lodashButBetter/isEmpty';
import isUndefined from '~utils/lodashButBetter/isUndefined';
import { metaAttribute, MetaConstants } from '~utils/metaAttribute';
import { getStyledProps } from '~components/Box/styledProps';
import type { StyledPropsBlade } from '~components/Box/styledProps';
import BaseBox from '~components/Box/BaseBox';
import { FormHint } from '~components/Form';
import { SelectorLabel } from '~components/Form/Selector/SelectorLabel';
import { SelectorTitle } from '~components/Form/Selector/SelectorTitle';
import { SelectorSupportText } from '~components/Form/Selector/SelectorSupportText';
import { SelectorInput } from '~components/Form/Selector/SelectorInput';
import type { BladeElementRef, TestID } from '~utils/types';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';
import { throwBladeError } from '~utils/logger';
import { makeSize, useTheme } from '~utils';

type OnChange = ({
  isChecked,
  event,
  value,
}: {
  isChecked: boolean;
  event?: React.ChangeEvent;
  value?: string;
}) => void;

type CheckboxProps = {
  /**
   * If `true`, The checkbox will be checked. This also makes the checkbox controlled
   * Use `onChange` to update its value
   *
   * @default false
   */
  isChecked?: boolean;
  /**
   * If `true`, the checkbox will be initially checked. This also makes the checkbox uncontrolled
   *
   * @default false
   */
  defaultChecked?: boolean;
  /**
   * The callback invoked when the checked state of the `Checkbox` changes.
   */
  onChange?: OnChange;
  /**
   * Sets the label of the checkbox
   */
  children?: React.ReactNode;
  /**
   * Help text for the checkbox
   */
  helpText?: string;
  /**
   * Error text for the checkbox
   *
   * Renders when `validationState` is set to 'error'
   */
  errorText?: string;
  /**
   * If `true`, the checkbox will be indeterminate.
   * This does not modify the isChecked property.
   *
   * @default false
   */
  isIndeterminate?: boolean;
  /**
   * The name of the input field in a checkbox
   * (Useful for form submission).
   */
  name?: string;
  /**
   * The value to be used in the checkbox input.
   * This is the value that will be returned on form submission.
   */
  value?: string;
  /**
   * If `true`, the checkbox will be disabled
   *
   * @default false
   */
  isDisabled?: boolean;
  /**
   * If `true`, the checkbox input is marked as required,
   * and `required` attribute will be added
   *
   * @default false
   */
  isRequired?: boolean;
  /**
   * If `error`, the checkbox input is marked as invalid,
   * and `invalid` attribute will be added
   */
  validationState?: 'error' | 'none';
  /**
   * Size of the checkbox
   *
   * @default "medium"
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Sets the tab-index property on checkbox element
   *
   */
  tabIndex?: number;
} & TestID &
  StyledPropsBlade;

const _Checkbox: React.ForwardRefRenderFunction<BladeElementRef, CheckboxProps> = (
  {
    defaultChecked,
    validationState,
    isChecked,
    isDisabled,
    isIndeterminate,
    isRequired,
    name,
    onChange,
    value,
    children,
    helpText,
    errorText,
    size = 'medium',
    tabIndex,
    testID,
    ...styledProps
  },
  ref,
) => {
  const groupProps = useCheckboxGroupContext();

  // ban certain props in checkbox while inside group
  const hasValidationState = !isUndefined(validationState);
  const hasName = !isUndefined(name);
  const hasDefaultChecked = !isUndefined(defaultChecked);
  const hasIsChecked = !isUndefined(isChecked);
  const hasOnChange = !isUndefined(onChange);

  if (__DEV__) {
    if (
      (hasValidationState || hasName || hasDefaultChecked || hasIsChecked || hasOnChange) &&
      !isEmpty(groupProps)
    ) {
      const props = [
        hasValidationState ? 'validationState' : undefined,
        hasName ? 'name' : undefined,
        hasDefaultChecked ? 'defaultChecked' : undefined,
        hasIsChecked ? 'isChecked' : undefined,
        hasOnChange ? 'onChange' : undefined,
      ]
        .filter(Boolean)
        .join(',');

      throwBladeError({
        message: `Cannot set \`${props}\` on <Checkbox /> when it's inside <CheckboxGroup />, Please set it on the <CheckboxGroup /> itself`,
        moduleName: 'Checkbox',
      });
    }

    // mandate value prop when using inside group
    if (!value && !isEmpty(groupProps)) {
      throw new Error(
        `[Blade Checkbox]: <CheckboxGroup /> requires that you pass unique "value" prop to each <Checkbox />
      <CheckboxGroup>
        <Checkbox value="apple">Apple</Checkbox>
        <Checkbox value="mango">Mango</Checkbox>
      </CheckboxGroup>
      `,
      );
    }
  }

  const _validationState = validationState ?? groupProps?.validationState;
  const _hasError = _validationState === 'error';
  const _isDisabled = isDisabled ?? groupProps?.isDisabled;
  const _isRequired = Boolean(
    isRequired || groupProps?.isRequired || groupProps?.necessityIndicator === 'required',
  );
  const _name = name ?? groupProps?.name;
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
  const _isChecked = isChecked ?? groupProps?.state?.isChecked(value!);
  const _size = groupProps.size ?? size;
  const { theme } = useTheme();
  const formHintSize = {
    small: 'medium',
    medium: 'medium',
    large: 'large',
  } as const;

  const showSupportingText = helpText;

  const handleChange: OnChange = ({ isChecked, event, value }) => {
    if (isChecked) {
      groupProps?.state?.addValue(value!);
    } else {
      groupProps?.state?.removeValue(value!);
    }

    onChange?.({ isChecked, event, value });
  };

  const { state, ids, inputProps } = useCheckbox({
    defaultChecked,
    isChecked: _isChecked,
    isIndeterminate,
    hasError: _hasError,
    hasHelperText: Boolean(showSupportingText),
    isDisabled: _isDisabled,
    isRequired: _isRequired,
    name: _name,
    value,
    onChange: handleChange,
  });

  // Checkbox icon's size & margin + margin-left of SelectorTitle which is 2
  const helpTextLeftSpacing = makeSize(checkboxSizes.icon[size].width + theme.spacing[3]);

  return (
    <BaseBox
      {...metaAttribute({ name: MetaConstants.Checkbox, testID })}
      {...getStyledProps(styledProps)}
    >
      <SelectorLabel
        componentName={MetaConstants.CheckboxLabel}
        inputProps={state.isReactNative ? inputProps : {}}
      >
        <BaseBox display="flex" flexDirection="column">
          <BaseBox display="flex" flexDirection="row" cursor={isDisabled ? "not-allowed" :  "pointer"}>
            <SelectorInput
              hoverTokens={checkboxHoverTokens}
              isChecked={state.isChecked || Boolean(isIndeterminate)}
              isDisabled={_isDisabled}
              hasError={_hasError}
              inputProps={inputProps}
              tabIndex={tabIndex}
              ref={ref}
            />
            <CheckboxIcon
              size={_size}
              isChecked={state.isChecked}
              isIndeterminate={isIndeterminate}
              isDisabled={_isDisabled}
              isNegative={_hasError}
            />
            {children ? (
              <SelectorTitle size={_size} isDisabled={_isDisabled}>
                {children}
              </SelectorTitle>
            ) : null}
          </BaseBox>
          {showSupportingText ? (
            <BaseBox marginLeft={helpTextLeftSpacing}>
              <SelectorSupportText size={_size} id={ids?.helpTextId}>
                {helpText}
              </SelectorSupportText>
            </BaseBox>
          ) : null}
        </BaseBox>
      </SelectorLabel>
      <FormHint
        size={formHintSize[_size]}
        errorText={errorText}
        errorTextId={ids?.errorTextId}
        type={validationState === 'error' ? 'error' : 'help'}
      />
    </BaseBox>
  );
};

const Checkbox = assignWithoutSideEffects(React.forwardRef(_Checkbox), {
  displayName: 'Checkbox',
});

export type { CheckboxProps };
export { Checkbox };
