// packages/blade/src/components/Form/CharacterCounter/CharacterCounter.tsx
import type { ReactElement } from 'react';
import { hintTextSize } from '../formTokens';
import { Text } from '~components/Typography';

type CharacterCounterProps = {
  currentCount: number;
  maxCount: number;
  size?: 'medium' | 'large';
};

export const CharacterCounter = ({
  currentCount,
  maxCount,
  size = 'medium',
}: CharacterCounterProps): ReactElement => (
  <Text
    variant="caption"
    size={hintTextSize[size]}
    weight="regular"
    color="surface.text.gray.muted"
  >
    {currentCount}/{maxCount}
  </Text>
);

// packages/blade-svelte/src/components/Input/_Form/CharacterCounter.svelte
<script lang="ts">
  import { hintTextSize } from '@razorpay/blade-core/styles';
  import Text from '../../Typography/Text/Text.svelte';
  import type { CharacterCounterProps } from './types';

  let { currentCount, maxCount, size = 'medium' }: CharacterCounterProps = $props();

  const textSize = $derived(hintTextSize[size]);
</script>

<Text variant="caption" size={textSize} weight="regular" color="surface.text.gray.muted">
  {currentCount}/{maxCount}
</Text>
