// packages/blade/src/components/Input/BaseInput/BaseInputVisuals.tsx
/* eslint-disable @typescript-eslint/explicit-function-return-type */
import React from 'react';
import type { ReactElement } from 'react';
import type { BaseInputProps } from './BaseInput';
import BaseBox from '~components/Box/BaseBox';
import { Text } from '~components/Typography';
import type { BaseBoxProps, SpacingValueType } from '~components/Box/BaseBox';
import type { IconColors } from '~components/Icons';
import { isValidAllowedChildren } from '~utils/isValidAllowedChildren';
import { throwBladeError } from '~utils/logger';
import { Tooltip } from '~components/Tooltip';
import { Box } from '~components/Box';
import { isReactNative } from '~utils';

type InputVisuals = Pick<
  BaseInputProps,
  | 'leadingIcon'
  | 'prefix'
  | 'trailingInteractionElement'
  | 'onTrailingInteractionElementClick'
  | 'leadingInteractionElement'
  | 'suffix'
  | 'trailingIcon'
  | 'isDisabled'
  | 'validationState'
  | 'size'
  | 'trailingButton'
  | 'showHintsAsTooltip'
  | 'errorText'
  | 'successText'
> & {
  size: NonNullable<BaseInputProps['size']>;
};

const getVisualContainerStyles = (): Pick<
  BaseBoxProps,
  'display' | 'flexDirection' | 'alignItems' | 'alignSelf'
> => ({
  display: 'flex',
  flexDirection: 'row',
  alignItems: 'center',
  alignSelf: 'center',
});

const trailingIconColor: Record<NonNullable<InputVisuals['validationState']>, IconColors> = {
  none: 'surface.icon.gray.subtle',
  error: 'feedback.icon.negative.intense',
  success: 'feedback.icon.positive.intense',
};

const iconSize = {
  medium: 'medium',
  large: 'large',
} as const;

const textSize = {
  medium: 'medium',
  large: 'large',
} as const;

const getPrefixStyles = ({
  hasLeadingIcon,
  hasPrefix,
}: {
  hasLeadingIcon: boolean;
  hasPrefix: boolean;
}): Pick<BaseBoxProps, 'paddingLeft'> => {
  if (hasPrefix && hasLeadingIcon) {
    return {
      paddingLeft: 'spacing.3',
    };
  }

  if (hasPrefix && !hasLeadingIcon) {
    return {
      paddingLeft: 'spacing.4',
    };
  }

  return {
    paddingLeft: 'spacing.0',
  };
};

const getInteractionElementStyles = ({
  hasTrailingIcon,
  hasLeadingInteractionElement,
  hasTrailingInteractionElement,
  hasSuffix,
  hasTrailingButton,
}: {
  hasTrailingIcon: boolean;
  hasLeadingInteractionElement?: boolean;
  hasTrailingInteractionElement?: boolean;
  hasSuffix: boolean;
  hasTrailingButton: boolean;
}): SpacingValueType => {
  if (hasTrailingInteractionElement && (hasSuffix || hasTrailingIcon || hasTrailingButton)) {
    return 'spacing.2';
  }

  if (hasTrailingInteractionElement && !hasSuffix && !hasTrailingIcon && !hasTrailingButton) {
    return 'spacing.4';
  }

  if (hasLeadingInteractionElement) {
    return 'spacing.3';
  }

  return 'spacing.0';
};

const getSuffixStyles = ({
  hasTrailingIcon,
  hasSuffix,
  hasTrailingButton,
}: {
  hasTrailingIcon: boolean;
  hasSuffix: boolean;
  hasTrailingButton: boolean;
}): Pick<BaseBoxProps, 'paddingRight'> => {
  if (hasSuffix && (hasTrailingIcon || hasTrailingButton)) {
    return {
      paddingRight: 'spacing.3',
    };
  }

  if (hasSuffix && !hasTrailingIcon && !hasTrailingButton) {
    return {
      paddingRight: 'spacing.4',
    };
  }

  return {
    paddingRight: 'spacing.0',
  };
};

const getTrailingIconStyles = ({
  hasTrailingIcon,
  hasTrailingButton,
}: {
  hasTrailingIcon: boolean;
  hasTrailingButton: boolean;
}): Pick<BaseBoxProps, 'paddingRight'> => {
  if (hasTrailingIcon && hasTrailingButton) {
    return {
      paddingRight: 'spacing.3',
    };
  }

  if (hasTrailingIcon && !hasTrailingButton) {
    return {
      paddingRight: 'spacing.4',
    };
  }

  return {
    paddingRight: 'spacing.0',
  };
};

export const getInputVisualsToBeRendered = ({
  leadingIcon,
  prefix,
  trailingInteractionElement,
  leadingInteractionElement,
  suffix,
  trailingIcon,
  trailingButton,
}: InputVisuals) => ({
  hasLeadingIcon: Boolean(leadingIcon),
  hasPrefix: Boolean(prefix),
  hasTrailingInteractionElement: Boolean(trailingInteractionElement),
  hasLeadingInteractionElement: Boolean(leadingInteractionElement),
  hasSuffix: Boolean(suffix),
  hasTrailingIcon: Boolean(trailingIcon),
  hasTrailingButton: Boolean(trailingButton),
});

const getTooltipContent = ({
  validationState,
  errorText,
  successText,
}: {
  validationState: BaseInputProps['validationState'];
  errorText: BaseInputProps['errorText'];
  successText: BaseInputProps['errorText'];
}): string => {
  if (validationState === 'error' && errorText) {
    return errorText;
  }

  if (validationState === 'success' && successText) {
    return successText;
  }

  return '';
};

const ValidationIconTooltip = ({
  children,
  validationState,
  errorText,
  successText,
  showHintsAsTooltip,
}: {
  children: ReactElement;
  validationState: BaseInputProps['validationState'];
  errorText: BaseInputProps['errorText'];
  successText: BaseInputProps['errorText'];
  showHintsAsTooltip: BaseInputProps['showHintsAsTooltip'];
}) => {
  if (
    (showHintsAsTooltip && validationState === 'error' && errorText) ||
    (validationState === 'success' && successText)
  ) {
    return (
      <Tooltip content={getTooltipContent({ validationState, errorText, successText })}>
        <Box display="flex" justifyContent="center" alignItems="center">
          {children}
        </Box>
      </Tooltip>
    );
  }

  return children;
};

export const BaseInputVisuals = ({
  leadingIcon: LeadingIcon,
  prefix,
  trailingInteractionElement,
  onTrailingInteractionElementClick,
  leadingInteractionElement,
  suffix,
  trailingIcon: TrailingIcon,
  isDisabled,
  validationState = 'none',
  size,
  showHintsAsTooltip,
  errorText,
  successText,
  trailingButton: TrailingButton,
}: InputVisuals): ReactElement | null => {
  const {
    hasLeadingIcon,
    hasPrefix,
    hasSuffix,
    hasTrailingInteractionElement,
    hasLeadingInteractionElement,
    hasTrailingIcon,
    hasTrailingButton,
  } = getInputVisualsToBeRendered({
    leadingIcon: LeadingIcon,
    prefix,
    leadingInteractionElement,
    trailingInteractionElement,
    suffix,
    trailingIcon: TrailingIcon,
    trailingButton: TrailingButton,
    size,
  });

  const hasLeadingVisuals = hasLeadingInteractionElement || hasLeadingIcon || hasPrefix;
  const hasTrailingVisuals =
    hasTrailingInteractionElement || hasSuffix || hasTrailingIcon || hasTrailingButton;

  if (__DEV__) {
    if (hasTrailingButton && !isValidAllowedChildren(TrailingButton, 'Link')) {
      throwBladeError({
        message: 'trailingButton must be a valid Blade Link component',
        moduleName: 'BaseInput',
      });
    }
  }

  if (hasLeadingVisuals) {
    return (
      <BaseBox {...getVisualContainerStyles()}>
        {hasLeadingInteractionElement ? (
          <BaseBox
            paddingLeft={getInteractionElementStyles({
              hasTrailingIcon,
              hasLeadingInteractionElement,
              hasSuffix,
              hasTrailingButton,
            })}
            display="flex"
            alignItems="stretch"
            alignSelf="stretch"
          >
            {leadingInteractionElement}
          </BaseBox>
        ) : null}
        {LeadingIcon ? (
          <BaseBox paddingLeft="spacing.4" display="flex">
            <LeadingIcon
              size={iconSize[size]}
              color={isDisabled ? 'surface.icon.gray.disabled' : 'surface.icon.gray.muted'}
            />
          </BaseBox>
        ) : null}
        {hasPrefix ? (
          <BaseBox {...getPrefixStyles({ hasLeadingIcon, hasPrefix })}>
            <Text
              size={textSize[size]}
              variant="body"
              weight="regular"
              color={isDisabled ? 'surface.text.gray.disabled' : 'surface.text.gray.subtle'}
            >
              {prefix}
            </Text>
          </BaseBox>
        ) : null}
      </BaseBox>
    );
  }

  if (hasTrailingVisuals && hasTrailingInteractionElement) {
    return (
      <BaseBox {...getVisualContainerStyles()} alignSelf="stretch">
        <BaseBox
          paddingRight={getInteractionElementStyles({
            hasTrailingIcon,
            hasTrailingInteractionElement,
            hasSuffix,
            hasTrailingButton,
          })}
          display="flex"
          alignItems="stretch"
          alignSelf="stretch"
          {...(!isReactNative() && { onClick: onTrailingInteractionElementClick })}
        >
          {trailingInteractionElement}
        </BaseBox>
      </BaseBox>
    );
  }

  if (hasTrailingVisuals) {
    return (
      <BaseBox alignSelf="stretch" alignItems="stretch" {...getVisualContainerStyles()}>
        {hasSuffix ? (
          <BaseBox {...getSuffixStyles({ hasTrailingIcon, hasSuffix, hasTrailingButton })}>
            <Text
              size={textSize[size]}
              variant="body"
              weight="regular"
              color={isDisabled ? 'surface.text.gray.disabled' : 'surface.text.gray.subtle'}
            >
              {suffix}
            </Text>
          </BaseBox>
        ) : null}
        {TrailingIcon ? (
          <BaseBox
            display="flex"
            justifyContent="center"
            alignItems="center"
            {...getTrailingIconStyles({ hasTrailingIcon, hasTrailingButton })}
          >
            <ValidationIconTooltip
              showHintsAsTooltip={showHintsAsTooltip}
              errorText={errorText}
              successText={successText}
              validationState={validationState}
            >
              <TrailingIcon
                size={iconSize[size]}
                color={
                  isDisabled ? 'interactive.icon.gray.disabled' : trailingIconColor[validationState]
                }
              />
            </ValidationIconTooltip>
          </BaseBox>
        ) : null}
        {TrailingButton ? (
          <BaseBox paddingRight="spacing.4" display="flex">
            {React.cloneElement(TrailingButton, {
              size,
              variant: 'button',
              isDisabled,
            })}
          </BaseBox>
        ) : null}
      </BaseBox>
    );
  }

  return null;
};

// packages/blade-svelte/src/components/Input/BaseInput/BaseInputVisuals.svelte
<script lang="ts">
  import type { BaseInputVisualsProps, ValidationState } from './types';
  import Text from '../../Typography/Text/Text.svelte';
  import {
    baseInputIconSize,
    baseInputTextSize,
    getInputVisualsClasses,
    getVisualIconClasses,
    getVisualTextClasses,
    getInteractionElementClasses,
    getTrailingButtonClasses,
  } from '@razorpay/blade-core/styles';
  import type { IconColor } from '../../Icons/types';

  let {
    type,
    size,
    isDisabled = false,
    validationState = 'none',
    leadingIcon: LeadingIcon,
    trailingIcon: TrailingIcon,
    prefix,
    suffix,
    trailingInteractionElement,
    leadingInteractionElement,
    trailingButton,
    hasOtherTrailingElements = false,
  }: BaseInputVisualsProps = $props();

  // Determine what visuals to show
  const hasLeadingIcon = $derived(Boolean(LeadingIcon));
  const hasTrailingIcon = $derived(Boolean(TrailingIcon));
  const hasPrefix = $derived(Boolean(prefix));
  const hasSuffix = $derived(Boolean(suffix));
  const hasTrailingInteractionElement = $derived(Boolean(trailingInteractionElement));
  const hasLeadingInteractionElement = $derived(Boolean(leadingInteractionElement));
  const hasTrailingButton = $derived(Boolean(trailingButton));

  // Check if we have any visuals for this type
  const hasLeadingVisuals = $derived(
    type === 'leading' && (hasLeadingInteractionElement || hasLeadingIcon || hasPrefix)
  );

  const hasTrailingVisuals = $derived(
    type === 'trailing' && (hasTrailingInteractionElement || hasSuffix || hasTrailingIcon || hasTrailingButton)
  );

  // Get icon size
  const iconSize = $derived(baseInputIconSize[size] as 'small' | 'medium' | 'large');

  // Get text size
  const textSize = $derived(baseInputTextSize[size] as 'small' | 'medium' | 'large');

  // Trailing icon color based on validation state
  const trailingIconColor: Record<ValidationState, IconColor> = {
    none: 'surface.icon.gray.subtle',
    error: 'feedback.icon.negative.intense',
    success: 'feedback.icon.positive.intense',
  };

  // CSS classes
  const containerClasses = $derived(getInputVisualsClasses({ type }));
</script>

{#if type === 'leading' && hasLeadingVisuals}
  <div class={containerClasses}>
    {#if hasLeadingInteractionElement && leadingInteractionElement}
      <div class={getInteractionElementClasses('leading')}>
        {@render leadingInteractionElement()}
      </div>
    {/if}

    {#if LeadingIcon}
      <div class={getVisualIconClasses('leading')}>
        <LeadingIcon
          size={iconSize}
          color={isDisabled ? 'surface.icon.gray.disabled' : 'surface.icon.gray.muted'}
        />
      </div>
    {/if}

    {#if hasPrefix}
      <div class={getVisualTextClasses('prefix', hasLeadingIcon)}>
        <Text
          size={textSize}
          variant="body"
          weight="regular"
          color={isDisabled ? 'surface.text.gray.disabled' : 'surface.text.gray.muted'}
        >
          {prefix}
        </Text>
      </div>
    {/if}
  </div>
{/if}

{#if type === 'trailing' && hasTrailingVisuals}
  <div class={containerClasses}>
    {#if hasTrailingInteractionElement && trailingInteractionElement}
      <div class={getInteractionElementClasses('trailing', hasOtherTrailingElements)}>
        {@render trailingInteractionElement()}
      </div>
    {/if}

    {#if hasSuffix}
      <div class={getVisualTextClasses('suffix', hasTrailingIcon || hasTrailingButton)}>
        <Text
          size={textSize}
          variant="body"
          weight="regular"
          color={isDisabled ? 'surface.text.gray.disabled' : 'surface.text.gray.subtle'}
        >
          {suffix}
        </Text>
      </div>
    {/if}

    {#if TrailingIcon}
      <div class={getVisualIconClasses('trailing')}>
        <TrailingIcon
          size={iconSize}
          color={isDisabled ? 'interactive.icon.gray.disabled' : trailingIconColor[validationState ?? 'none']}
        />
      </div>
    {/if}

    {#if hasTrailingButton && trailingButton}
      <div class={getTrailingButtonClasses()}>
        {@render trailingButton()}
      </div>
    {/if}
  </div>
{/if}
