// packages/blade/src/components/Checkbox/CheckboxGroup/CheckboxGroup.tsx
import React from 'react';

import { FormLabel, FormHint } from '~components/Form';
import BaseBox from '~components/Box/BaseBox';
import { SelectorGroupField } from '~components/Form/Selector/SelectorGroupField';
import { getStyledProps } from '~components/Box/styledProps';
import { useBreakpoint } from '~utils';
import { useTheme } from '~components/BladeProvider';
import { makeAnalyticsAttribute } from '~utils/makeAnalyticsAttribute';

import { checkboxSizes } from '../checkboxTokens';

import { CheckboxGroupProvider } from './CheckboxGroupContext';
import { useCheckboxGroup } from './useCheckboxGroup';

import type { StyledPropsBlade } from '~components/Box/styledProps';
import type { DataAnalyticsAttribute, TestID } from '~utils/types';

type CheckboxGroupProps = {
  /**
   * Accepts multiple checkboxes as children
   */
  children: React.ReactNode;
  /**
   * Help text of the checkbox group
   */
  helpText?: string;
  /**
   * Error text of the checkbox group
   * Renders when `validationState` is set to 'error'
   *
   * Overrides helpText
   */
  errorText?: string;
  /**
   * Sets the error state of the CheckboxGroup
   * If set to `error` it will render the `errorText` of the group,
   * and propagate `invalid` prop to every checkbox
   */
  validationState?: 'error' | 'none';
  /**
   * Renders a necessity indicator after CheckboxGroup label
   *
   * If set to `undefined` it renders nothing.
   */
  necessityIndicator?: 'required' | 'optional' | 'none';
  /**
   * Sets the disabled state of the CheckboxGroup
   * If set to `true` it propagate down to all the checkboxes
   *
   * @default false
   */
  isDisabled?: boolean;
  /**
   * Sets the required state of the CheckboxGroup
   * @default false
   */
  isRequired?: boolean;
  /**
   * Renders the label of the checkbox group
   */
  label?: string;
  /**
   * Sets the position of the label
   *
   * @default 'top'
   */
  labelPosition?: 'top' | 'left';
  /**
   * Initial value of the checkbox group
   */
  defaultValue?: string[];
  /**
   * value of the checkbox group
   *
   * Use `onChange` to update its value
   */
  value?: string[];
  /**
   * The callback invoked when any of the checkbox's state changes
   */
  onChange?: ({ name, values }: { name: string; values: string[] }) => void;
  /**
   * The name of the input field in a checkbox
   * (Useful for form submission).
   */
  name?: string;
  /**
   * Size of the checkbox
   *
   * @default "medium"
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Orientation of the checkbox group
   *
   * @default "vertical"
   */
  orientation?: 'vertical' | 'horizontal';
} & TestID &
  DataAnalyticsAttribute &
  StyledPropsBlade;

const CheckboxGroup = ({
  children,
  label,
  helpText,
  isDisabled = false,
  isRequired = false,
  necessityIndicator = 'none',
  labelPosition = 'top',
  validationState,
  errorText,
  name,
  defaultValue,
  onChange,
  value,
  size = 'medium',
  testID,
  orientation = 'vertical',
  flexWrap = 'nowrap',
  ...rest
}: CheckboxGroupProps): React.ReactElement => {
  const { contextValue, ids } = useCheckboxGroup({
    defaultValue,
    onChange,
    value,
    isDisabled,
    necessityIndicator,
    isRequired,
    name,
    labelPosition,
    validationState,
    size,
  });

  const { theme } = useTheme();
  const showError = validationState === 'error' && errorText;
  const showHelpText = !showError && helpText;
  const accessibilityText = `,${showError ? errorText : ''} ${showHelpText ? helpText : ''}`;
  const { matchedDeviceType } = useBreakpoint({ breakpoints: theme.breakpoints });
  const gap = checkboxSizes.group.gap[size][matchedDeviceType];

  return (
    <CheckboxGroupProvider value={contextValue}>
      <BaseBox {...getStyledProps(rest)}>
        <SelectorGroupField
          position={labelPosition}
          labelledBy={ids.labelId}
          componentName="checkbox-group"
          testID={testID}
          {...makeAnalyticsAttribute(rest)}
        >
          {label ? (
            <FormLabel
              as="span"
              necessityIndicator={necessityIndicator}
              position={labelPosition}
              id={ids.labelId}
              accessibilityText={accessibilityText}
              size={size}
            >
              {label}
            </FormLabel>
          ) : null}
          <BaseBox>
            <BaseBox
              display="flex"
              flexDirection={orientation === 'horizontal' ? 'row' : 'column'}
              gap={gap}
              flexWrap={flexWrap}
            >
              {React.Children.map(children, (child, index) => {
                return <BaseBox key={index}>{child}</BaseBox>;
              })}
            </BaseBox>
            <FormHint
              size={size}
              errorText={errorText}
              helpText={helpText}
              type={validationState === 'error' ? 'error' : 'help'}
            />
          </BaseBox>
        </SelectorGroupField>
      </BaseBox>
    </CheckboxGroupProvider>
  );
};

export type { CheckboxGroupProps };
export { CheckboxGroup };

// packages/blade-svelte/src/components/Checkbox/CheckboxGroup.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import {
    metaAttribute,
    MetaConstants,
    makeAccessible,
    makeAnalyticsAttribute,
    getStyledPropsClasses,
  } from '@razorpay/blade-core/utils';
  import {
    getCheckboxGroupFieldClasses,
    getCheckboxGroupOptionsClasses,
    getCheckboxGroupLabelSizeClass,
    getCheckboxGroupTemplateClasses,
    getCheckboxHintClasses,
  } from '@razorpay/blade-core/styles';
  import { InfoIcon } from '../Icons';
  import { setCheckboxGroupContext } from './checkboxContext';
  import type { CheckboxGroupProps, CheckboxGroupContextType, State } from './types';

  const templateClasses = getCheckboxGroupTemplateClasses();

  let {
    children,
    label,
    helpText,
    errorText,
    validationState = 'none',
    necessityIndicator = 'none',
    isDisabled = false,
    isRequired = false,
    labelPosition = 'top',
    defaultValue,
    value: controlledValue,
    onChange,
    name,
    size = 'medium',
    orientation = 'vertical',
    flexWrap = 'nowrap',
    labelSuffix,
    labelTrailing,
    testID,
    ...rest
  }: CheckboxGroupProps = $props();

  // ── ids ── (initial-only reads of `name`)
  const idBase = `checkbox-group-${Math.random().toString(36).slice(2, 8)}`;
  const labelId = `${idBase}-label`;
  const fallbackName = untrack(() => name) ?? idBase;

  // ── Controllable value[] (Chip pattern) ── (initial-only seed)
  const initialValue = untrack(() => controlledValue ?? defaultValue ?? []);
  let checkedValues = $state<string[]>([...initialValue]);

  $effect(() => {
    if (controlledValue !== undefined) {
      checkedValues = [...controlledValue];
    }
  });

  const groupState: State = {
    get value() {
      return checkedValues;
    },
    isChecked(val: string): boolean {
      return checkedValues.includes(val);
    },
    addValue(val: string) {
      if (isDisabled) return;
      if (!checkedValues.includes(val)) {
        checkedValues = [...checkedValues, val];
      }
      onChange?.({ name: fallbackName, values: checkedValues });
    },
    removeValue(val: string) {
      if (isDisabled) return;
      if (checkedValues.includes(val)) {
        checkedValues = checkedValues.filter((existing) => existing !== val);
      }
      onChange?.({ name: fallbackName, values: checkedValues });
    },
  };

  const contextValue: CheckboxGroupContextType = {
    get validationState() {
      return validationState;
    },
    get isDisabled() {
      return isDisabled;
    },
    get isRequired() {
      return isRequired;
    },
    get labelPosition() {
      return labelPosition;
    },
    get name() {
      return fallbackName;
    },
    get necessityIndicator() {
      return necessityIndicator;
    },
    get size() {
      return size;
    },
    state: groupState,
  };

  setCheckboxGroupContext(() => contextValue);

  const showError = $derived(validationState === 'error' && Boolean(errorText));
  const showHelpText = $derived(!showError && Boolean(helpText));

  // React FormHint icon sizing: small/medium hint -> 'small', large -> 'medium'.
  const hintIconSize = $derived(size === 'large' ? 'medium' : 'small');

  const fieldClasses = $derived(getCheckboxGroupFieldClasses({ labelPosition }));
  const optionsClasses = $derived(getCheckboxGroupOptionsClasses({ orientation, size }));
  const labelSizeClass = $derived(getCheckboxGroupLabelSizeClass(size));
  const hintClasses = $derived(
    getCheckboxHintClasses({ size, type: validationState === 'error' ? 'error' : 'help' }),
  );

  const necessityClass = $derived(
    necessityIndicator === 'required'
      ? templateClasses.necessityRequired
      : necessityIndicator === 'optional'
        ? templateClasses.necessityOptional
        : '',
  );

  const styledProps = $derived(getStyledPropsClasses(rest));
  const wrapperClasses = $derived(
    [...(styledProps.classes || [])].filter(Boolean).join(' ') || undefined,
  );
  const wrapperStyles = $derived(
    [
      ...Object.entries(styledProps.inlineStyles || {}).map(([prop, val]) => `${prop}: ${val}`),
      `flex-wrap: ${flexWrap}`,
    ].join('; ') || undefined,
  );

  const optionsStyles = $derived(`flex-wrap: ${flexWrap}`);

  const metaAttrs = $derived(metaAttribute({ name: MetaConstants.CheckboxGroup, testID }));
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
  const a11yAttrs = $derived(
    makeAccessible({
      role: 'group',
      labelledBy: label ? labelId : undefined,
    }),
  );
</script>

<div class={wrapperClasses} style={wrapperStyles} {...metaAttrs} {...analyticsAttrs}>
  <div class={fieldClasses} {...a11yAttrs}>
    {#if label}
      <span
        id={labelId}
        class={[templateClasses.groupLabel, labelSizeClass].filter(Boolean).join(' ')}
      >
        <span class={[templateClasses.labelRow].join(' ')}>
          <span class={necessityClass}>{label}</span>
          {#if labelSuffix}
            <span class={templateClasses.labelSuffix}>{@render labelSuffix()}</span>
          {/if}
          {#if labelTrailing}
            <span class={templateClasses.labelTrailing}>{@render labelTrailing()}</span>
          {/if}
        </span>
      </span>
    {/if}
    <div>
      <div class={optionsClasses} style={optionsStyles}>
        {@render children()}
      </div>
      {#if showError}
        <span class={templateClasses.hintWrapper}>
          <span class={templateClasses.hintIcon}>
            <InfoIcon size={hintIconSize} color="feedback.icon.negative.intense" />
          </span>
          <span class={hintClasses}>{errorText}</span>
        </span>
      {:else if showHelpText}
        <span class={hintClasses}>{helpText}</span>
      {/if}
    </div>
  </div>
</div>
