// packages/blade/src/components/Input/PasswordInput/PasswordInput.tsx
import React from 'react';
import type { BaseInputProps } from '../BaseInput';
import { BaseInput } from '../BaseInput';
import { EyeIcon, EyeOffIcon } from '~components/Icons';
import BaseBox from '~components/Box/BaseBox';
import { CharacterCounter } from '~components/Form/CharacterCounter';
import { IconButton } from '~components/Button/IconButton';
import type { BladeElementRef } from '~utils/useBladeInnerRef';
import { useBladeInnerRef } from '~utils/useBladeInnerRef';
import type { StyledPropsBlade } from '~components/Box/styledProps';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';
import { MetaConstants } from '~utils/metaAttribute';

type PasswordInputExtraProps = {
  /**
   * Shows a reveal button to toggle password visibility
   *
   * @default true
   */
  showRevealButton?: boolean;

  /**
   * Displays asterisk (`*`) when `isRequired` is enabled
   *
   * @default none
   */
  necessityIndicator?: Exclude<BaseInputProps['necessityIndicator'], 'optional'>;

  /**
   * Determines what autoComplete suggestion type to show. Defaults to using platform heuristics.
   *
   * It's not recommended to turn this off in favor of safe password practices.
   * Providing `password` or `newPassword` is more informative to the platform for browser autofill or password managers.
   *
   * **Note**: Using `newPassword` on iOS has some [known issue](https://github.com/facebook/react-native/issues/21911) on React Native
   *
   * Internally it'll render platform specific attributes:
   *
   * - web: `autocomplete`
   * - iOS: `textContentType`
   * - android: `autoComplete`
   *
   */
  autoCompleteSuggestionType?: Extract<
    BaseInputProps['autoCompleteSuggestionType'],
    'none' | 'password' | 'newPassword'
  >;
};

type PasswordInputProps = Pick<
  BaseInputProps,
  | 'label'
  | 'accessibilityLabel'
  | 'labelPosition'
  | 'maxCharacters'
  | 'validationState'
  | 'errorText'
  | 'successText'
  | 'helpText'
  | 'isDisabled'
  | 'defaultValue'
  | 'placeholder'
  | 'isRequired'
  | 'value'
  | 'onChange'
  | 'onBlur'
  | 'onSubmit'
  | 'onFocus'
  | 'name'
  | 'autoFocus'
  | 'keyboardReturnKeyType'
  | 'autoCompleteSuggestionType'
  | 'testID'
> &
  PasswordInputExtraProps &
  StyledPropsBlade;

const _PasswordInput: React.ForwardRefRenderFunction<BladeElementRef, PasswordInputProps> = (
  {
    label,
    accessibilityLabel,
    labelPosition = 'top',
    showRevealButton = true,
    maxCharacters,
    validationState,
    errorText,
    successText,
    helpText,
    isDisabled = false,
    defaultValue,
    placeholder,
    isRequired = false,
    necessityIndicator = 'none',
    value,
    onChange,
    onFocus,
    onBlur,
    onSubmit,
    name,
    autoFocus = false,
    keyboardReturnKeyType = 'done',
    autoCompleteSuggestionType,
    testID,
    ...styledProps
  },
  ref,
) => {
  const inputRef = useBladeInnerRef(ref);
  const [isRevealed, setIsRevealed] = React.useState(false);
  const isEnabled = !isDisabled;

  // If input is disabled reveal button shouldn't be present and input should be masked
  const isRevealedAndEnabled = isRevealed && isEnabled;

  const toggleIsRevealed = (): void => setIsRevealed((revealed) => !revealed);
  const iconAccessibilityLabel = isRevealedAndEnabled ? 'Hide password' : 'Show password';
  const type = isRevealedAndEnabled ? 'text' : 'password';

  const revealButtonIcon = isRevealedAndEnabled ? EyeOffIcon : EyeIcon;
  const revealButton =
    showRevealButton && !isDisabled ? (
      <IconButton
        size="medium"
        icon={revealButtonIcon}
        onClick={toggleIsRevealed}
        accessibilityLabel={iconAccessibilityLabel}
      />
    ) : null;

  const trailingFooterSlot = (value?: string): React.ReactNode =>
    maxCharacters ? (
      <BaseBox marginTop="spacing.2" marginRight="spacing.1">
        <CharacterCounter currentCount={value?.length ?? 0} maxCount={maxCharacters} />
      </BaseBox>
    ) : null;

  return (
    <BaseInput
      ref={inputRef as React.Ref<HTMLInputElement>}
      componentName={MetaConstants.PasswordInput}
      id="password-field"
      label={label}
      accessibilityLabel={accessibilityLabel}
      hideLabelText={!Boolean(label)}
      labelPosition={labelPosition}
      type={type}
      interactionElement={revealButton}
      trailingFooterSlot={trailingFooterSlot}
      maxCharacters={maxCharacters}
      validationState={validationState}
      errorText={errorText}
      successText={successText}
      helpText={helpText}
      isDisabled={isDisabled}
      defaultValue={defaultValue}
      placeholder={placeholder}
      isRequired={isRequired}
      necessityIndicator={necessityIndicator}
      value={value}
      onChange={onChange}
      onBlur={onBlur}
      onSubmit={onSubmit}
      onFocus={onFocus}
      name={name}
      // eslint-disable-next-line jsx-a11y/no-autofocus
      autoFocus={autoFocus}
      autoCompleteSuggestionType={autoCompleteSuggestionType}
      keyboardReturnKeyType={keyboardReturnKeyType}
      autoCapitalize="none"
      testID={testID}
      {...styledProps}
    />
  );
};

// nosemgrep
const PasswordInput = assignWithoutSideEffects(React.forwardRef(_PasswordInput), {
  displayName: 'PasswordInput',
});

export { PasswordInputProps, PasswordInput };

// packages/blade-svelte/src/components/Input/PasswordInput/PasswordInput.svelte
<script lang="ts">
  import { makeAnalyticsAttribute } from '@razorpay/blade-core/utils';
  import BaseInput from '../BaseInput/BaseInput.svelte';
  import CharacterCounter from '../_Form/CharacterCounter.svelte';
  import IconButton from '../../Button/IconButton/IconButton.svelte';
  import { EyeIcon, EyeOffIcon } from '../../Icons';
  import { useFormId } from '../BaseInput/useFormId';
  import type { PasswordInputProps } from './types';

  let {
    label,
    accessibilityLabel,
    labelPosition = 'top',
    labelSuffix,
    labelTrailing,
    showRevealButton = true,
    necessityIndicator = 'none',
    autoCompleteSuggestionType,
    maxCharacters,
    validationState = 'none',
    errorText,
    successText,
    helpText,
    isDisabled = false,
    defaultValue,
    placeholder,
    isRequired = false,
    value,
    onChange,
    onFocus,
    onBlur,
    name,
    autoFocus = false,
    keyboardReturnKeyType = 'done',
    size = 'medium',
    testID,
    ...rest
  }: PasswordInputProps = $props();

  let baseInput = $state<{ focus: () => void; getInput: () => HTMLInputElement | null } | null>(
    null,
  );

  // If input is disabled the reveal button is hidden and the input stays masked.
  let isRevealed = $state(false);
  const isRevealedAndEnabled = $derived(isRevealed && !isDisabled);
  const inputType = $derived(isRevealedAndEnabled ? 'text' : 'password');
  const iconAccessibilityLabel = $derived(isRevealedAndEnabled ? 'Hide password' : 'Show password');

  const toggleIsRevealed = () => {
    isRevealed = !isRevealed;
  };

  const showRevealInteraction = $derived(showRevealButton && !isDisabled);

  export function focus(): void {
    baseInput?.focus();
  }
  export function getInput(): HTMLInputElement | null {
    return baseInput?.getInput() ?? null;
  }

  const ids = useFormId('passwordinput');
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
</script>

{#snippet revealButton()}
  <IconButton
    size="medium"
    icon={isRevealedAndEnabled ? EyeOffIcon : EyeIcon}
    accessibilityLabel={iconAccessibilityLabel}
    onClick={toggleIsRevealed}
  />
{/snippet}

{#snippet footerCounter(currentValue: string | undefined)}
  {#if maxCharacters}
    <CharacterCounter currentCount={currentValue?.length ?? 0} maxCount={maxCharacters} {size} />
  {/if}
{/snippet}

<BaseInput
  bind:this={baseInput}
  id={ids.baseId}
  componentName="password-input"
  label={label ?? ''}
  hideLabelText={!label}
  {accessibilityLabel}
  {labelPosition}
  {labelSuffix}
  {labelTrailing}
  {necessityIndicator}
  type={inputType}
  {placeholder}
  {defaultValue}
  {value}
  {name}
  {maxCharacters}
  {onChange}
  {onFocus}
  {onBlur}
  {isDisabled}
  {isRequired}
  trailingInteractionElement={showRevealInteraction ? revealButton : undefined}
  trailingFooterSlot={footerCounter}
  {validationState}
  {errorText}
  {successText}
  {helpText}
  {size}
  {autoFocus}
  {keyboardReturnKeyType}
  {autoCompleteSuggestionType}
  autoCapitalize="none"
  {testID}
  {...analyticsAttrs}
  {...rest}
/>
