// packages/blade-svelte/src/components/Tabs/TabPanel.svelte
<script lang="ts">
  import {
    metaAttribute,
    MetaConstants,
    makeAnalyticsAttribute,
  } from '@razorpay/blade-core/utils';
  import { getTabsClasses } from '@razorpay/blade-core/styles';
  import { getTabsContext } from './context';
  import type { TabPanelProps } from './types';

  const classes = getTabsClasses();

  let {
    children,
    value,
    testID,
    ...rest
  }: TabPanelProps = $props();

  const getCtx = getTabsContext();
  const ctx = $derived(getCtx());

  const isSelected = $derived(ctx.selectedValue === value);
  const panelId = $derived(`${ctx.baseId}-${value}-tabpanel`);
  const tabItemId = $derived(`${ctx.baseId}-${value}-tabitem`);

  const panelClasses = $derived(
    [classes.tabPanel, !isSelected && !ctx.isLazy ? classes.tabPanelHidden : '']
      .filter(Boolean)
      .join(' '),
  );

  const metaAttrs = metaAttribute({ name: MetaConstants.TabPanel, testID });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
</script>

{#if ctx.isLazy}
  {#if isSelected}
    <div
      id={panelId}
      class={classes.tabPanel}
      tabindex={0}
      role="tabpanel"
      aria-labelledby={tabItemId}
      {...metaAttrs}
      {...analyticsAttrs}
    >
      {@render children()}
    </div>
  {/if}
{:else}
  <div
    id={panelId}
    class={panelClasses}
    tabindex={0}
    role="tabpanel"
    aria-labelledby={tabItemId}
    aria-hidden={!isSelected}
    {...metaAttrs}
    {...analyticsAttrs}
  >
    {@render children()}
  </div>
{/if}

// packages/blade/src/components/Tabs/TabPanel.tsx
/* eslint-disable react/jsx-no-useless-fragment */
import React from 'react';
import type { TabPanelProps } from './types';
import { useTabsContext } from './TabsContext';
import { makeAccessible } from '~utils/makeAccessible';
import BaseBox from '~components/Box/BaseBox';

const TabPanel = ({ children, value }: TabPanelProps): React.ReactElement => {
  const { selectedValue, baseId } = useTabsContext();
  const isSelected = selectedValue === value;
  const panelId = `${baseId}-${value}-tabpanel`;
  const tabItemId = `${baseId}-${value}-tabitem`;

  return (
    <>
      {isSelected ? (
        <BaseBox
          id={panelId}
          tabIndex={0}
          {...makeAccessible({ role: 'tabpanel', labelledBy: tabItemId })}
        >
          {children}
        </BaseBox>
      ) : null}
    </>
  );
};

export { TabPanel };
