// packages/blade-svelte/src/components/BaseHeaderFooter/BaseFooter.svelte
<script lang="ts">
  import { metaAttribute, makeAnalyticsAttribute } from '@razorpay/blade-core/utils';
  import { baseFooterInnerClass, getDropdownTemplateClasses } from '@razorpay/blade-core/styles';
  import Divider from '../Divider/Divider.svelte';
  import type { BaseFooterProps } from './types';

  // Prevent tree-shaking of template classes used in compound selectors.
  void getDropdownTemplateClasses();

  let {
    children,
    showDivider = true,
    metaComponentName,
    testID,
    ...rest
  }: BaseFooterProps = $props();

  const metaAttrs = $derived(metaAttribute({ name: metaComponentName, testID }));
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
</script>

{#if showDivider}
  <Divider />
{/if}
<div class={baseFooterInnerClass} {...metaAttrs} {...analyticsAttrs}>
  {@render children?.()}
</div>

// packages/blade/src/components/BaseHeaderFooter/BaseFooter.tsx
import React from 'react';
import { Divider } from '~components/Divider';
import BaseBox from '~components/Box/BaseBox';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';
import { metaAttribute } from '~utils/metaAttribute';
import type { DataAnalyticsAttribute, TestID } from '~utils/types';
import type { BoxProps } from '~components/Box';
import { makeAnalyticsAttribute } from '~utils/makeAnalyticsAttribute';

type BaseFooterProps = {
  children: React.ReactNode;
  metaComponentName?: string;
  showDivider?: boolean;
  padding?: BoxProps['padding'];
} & TestID &
  DataAnalyticsAttribute;

const _BaseFooter = ({
  children,
  showDivider = true,
  metaComponentName,
  padding,
  testID,
  ...rest
}: BaseFooterProps): React.ReactElement => {
  return (
    <>
      {showDivider && <Divider />}
      <BaseBox
        {...metaAttribute({ name: metaComponentName, testID })}
        {...makeAnalyticsAttribute(rest)}
        padding={padding ?? { base: 'spacing.5', m: 'spacing.6' }}
        width="100%"
      >
        {children}
      </BaseBox>
    </>
  );
};

const BaseFooter = assignWithoutSideEffects(_BaseFooter, {
  componentId: 'BaseFooter',
});

export type { BaseFooterProps };
export { BaseFooter };
