// packages/blade/src/components/Tabs/Tabs.tsx
import React from 'react';
import type { TabsProps } from './types';
import { TabsContext } from './TabsContext';
import { useControllableState } from '~utils/useControllable';
import { useId } from '~utils/useId';
import BaseBox from '~components/Box/BaseBox';

const Tabs = ({
  children,
  defaultValue,
  value,
  onChange,
  orientation = 'horizontal',
  size = 'medium',
  variant = 'bordered',
  isFullWidthTabItem = false,
  isLazy = false,
}: TabsProps): React.ReactElement => {
  const baseId = useId('tabs');
  const [selectedValue, setSelectedValue] = useControllableState({
    defaultValue,
    value,
    onChange: (value) => {
      onChange?.(value);
    },
  });

  const isVertical = orientation === 'vertical';
  const contextValue = React.useMemo(
    () => ({
      baseId,
      selectedValue,
      isVertical,
      size,
      variant,
      isFullWidthTabItem,
      setSelectedValue,
      isLazy,
    }),
    [
      isFullWidthTabItem,
      baseId,
      isVertical,
      selectedValue,
      setSelectedValue,
      size,
      variant,
      isLazy,
    ],
  );

  return (
    <TabsContext.Provider value={contextValue}>
      <BaseBox display="flex" flexDirection={isVertical ? 'row' : 'column'}>
        {children}
      </BaseBox>
    </TabsContext.Provider>
  );
};

export { Tabs };

// packages/blade-svelte/src/components/Tabs/Tabs.svelte
<script module lang="ts">
  let nextTabsUid = 0;
</script>

<script lang="ts">
  import {
    metaAttribute,
    MetaConstants,
    makeAnalyticsAttribute,
  } from '@razorpay/blade-core/utils';
  import { getTabsClasses } from '@razorpay/blade-core/styles';
  import { setTabsContext } from './context';
  import type { TabsProps } from './types';

  const classes = getTabsClasses();

  let {
    children,
    defaultValue,
    value: controlledValue,
    onChange,
    orientation = 'horizontal',
    size = 'medium',
    variant = 'bordered',
    isFullWidthTabItem = false,
    isLazy = false,
    testID,
    ...rest
  }: TabsProps = $props();

  nextTabsUid += 1;
  const baseId = `tabs-${nextTabsUid}`;

  let internalValue = $state<string>(defaultValue ?? '');

  const selectedValue = $derived(
    controlledValue !== undefined ? controlledValue : internalValue,
  );

  const isVertical = $derived(orientation === 'vertical');

  const setSelectedValue = (newValue: string, skipOnChange?: boolean) => {
    if (controlledValue !== undefined) {
      if (!skipOnChange) {
        onChange?.(newValue);
      }
    } else {
      internalValue = newValue;
      if (!skipOnChange) {
        onChange?.(newValue);
      }
    }
  };

  setTabsContext(() => ({
    baseId,
    selectedValue,
    setSelectedValue,
    isVertical,
    size,
    variant,
    isFullWidthTabItem,
    isLazy,
  }));

  const wrapperClasses = $derived(
    [classes.tabsWrapper, isVertical ? classes.tabsVertical : classes.tabsHorizontal]
      .filter(Boolean)
      .join(' '),
  );

  const metaAttrs = metaAttribute({ name: MetaConstants.Tabs, testID });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
</script>

<div
  class={wrapperClasses}
  {...metaAttrs}
  {...analyticsAttrs}
>
  {@render children()}
</div>
