// packages/blade-svelte/src/components/Form/CharacterCounter/CharacterCounter.svelte
<script lang="ts">
  import type { CharacterCounterProps } from './types';
  import Text from '../../Typography/Text/Text.svelte';
  import { hintTextSize } from '@razorpay/blade-core/styles';

  let {
    currentCount,
    maxCount,
    size = 'medium',
  }: CharacterCounterProps = $props();

  const textSize = $derived(hintTextSize[size] as 'small' | 'medium');
</script>

<Text
  variant="caption"
  size={textSize}
  weight="regular"
  color="surface.text.gray.muted"
>
  {currentCount}/{maxCount}
</Text>

// packages/blade/src/components/Form/CharacterCounter/CharacterCounter.tsx
import type { ReactElement } from 'react';
import { hintTextSize } from '../formTokens';
import { Text } from '~components/Typography';

type CharacterCounterProps = {
  currentCount: number;
  maxCount: number;
  size?: 'xsmall' | 'small' | 'medium' | 'large';
};

export const CharacterCounter = ({
  currentCount,
  maxCount,
  size = 'medium',
}: CharacterCounterProps): ReactElement => (
  <Text
    variant="caption"
    size={hintTextSize[size]}
    weight="regular"
    color="surface.text.gray.muted"
  >
    {currentCount}/{maxCount}
  </Text>
);
