// packages/blade/src/components/Avatar/AvatarButton.tsx
import React from 'react';
import { StyledAvatarButton } from './StyledAvatarButton';
import type { AvatarButtonProps } from './types';
import { avatarTextSizeMapping, avatarIconSizeTokens } from './avatarTokens';
import BaseBox from '~components/Box/BaseBox';
import { makeAccessible } from '~utils/makeAccessible';
import { Heading, Text } from '~components/Typography';
import { getTextColorToken } from '~components/Button/BaseButton/BaseButton';
import type { IconColor } from '~components/Button/BaseButton/types';
import type { BaseTextProps } from '~components/Typography/BaseText/types';
import type { BladeElementRef } from '~utils/types';

const _AvatarButton: React.ForwardRefRenderFunction<BladeElementRef, AvatarButtonProps> = (
  {
    href,
    target,
    rel,
    variant = 'circle',
    color = 'neutral',
    size = 'medium',
    icon: Icon,
    imgProps,
    children,
    onBlur,
    onFocus,
    onClick,
    onMouseLeave,
    onMouseMove,
    onMouseDown,
    onPointerDown,
    onPointerEnter,
    onTouchStart,
    onTouchEnd,
    isSelected,
  },
  ref,
): React.ReactElement => {
  const isLink = Boolean(href);
  const isInteractive = Boolean(onClick || isLink);
  const as = isInteractive ? (href ? 'a' : 'button') : 'div';

  const defaultRel = target === '_blank' ? 'noreferrer noopener' : undefined;
  const iconColor = getTextColorToken({
    property: 'icon',
    variant: 'secondary',
    color,
    state: 'default',
  }) as IconColor;
  const textColor = getTextColorToken({
    property: 'text',
    variant: 'secondary',
    color,
    state: 'default',
  }) as BaseTextProps['color'];

  return (
    <StyledAvatarButton
      ref={ref as never}
      as={as as never}
      isInteractive={isInteractive}
      isSelected={isSelected}
      size={size}
      color={color}
      href={href}
      variant={variant}
      target={target}
      rel={rel ?? defaultRel}
      accessibilityProps={{
        ...makeAccessible({
          role: isInteractive ? (isLink ? 'link' : 'button') : 'presentation',
        }),
      }}
      onBlur={onBlur}
      onFocus={onFocus}
      onClick={onClick}
      onMouseLeave={onMouseLeave}
      onMouseMove={onMouseMove}
      onMouseDown={onMouseDown}
      onPointerDown={onPointerDown}
      onPointerEnter={onPointerEnter}
      onTouchStart={onTouchStart}
      onTouchEnd={onTouchEnd}
    >
      <BaseBox
        display="flex"
        flexDirection="row"
        alignItems="center"
        justifyContent="center"
        zIndex={1}
        height="100%"
      >
        {Icon ? (
          <BaseBox display="flex" justifyContent="center" alignItems="center">
            <Icon size={avatarIconSizeTokens[size]} color={iconColor} />
          </BaseBox>
        ) : null}

        {/* eslint-disable-next-line jsx-a11y/alt-text -- alt text is provided in imgProps */}
        {imgProps?.src ? <img {...imgProps} /> : null}

        {size === 'xlarge' ? (
          <Heading size={avatarTextSizeMapping[size]} weight="semibold" color={textColor}>
            {children}
          </Heading>
        ) : (
          <Text size={avatarTextSizeMapping[size]} weight="semibold" color={textColor}>
            {children}
          </Text>
        )}
      </BaseBox>
    </StyledAvatarButton>
  );
};

const AvatarButton = React.forwardRef(_AvatarButton);

export { AvatarButton };

// packages/blade-svelte/src/components/Avatar/AvatarButton.svelte
<script lang="ts">
  import { makeAccessible, type AriaRoles } from '@razorpay/blade-core/utils';
  import {
    getAvatarButtonClasses,
    getAvatarTemplateClasses,
    avatarIconSizeTokens,
    avatarTextSizeMapping,
    getButtonTextColorToken,
  } from '@razorpay/blade-core/styles';
  import BaseText from '../Typography/BaseText/BaseText.svelte';
  import Heading from '../Typography/Heading/Heading.svelte';
  import type { TextColors } from '../Typography/BaseText/types';
  import type { IconColor } from '../Icons/types';
  import type { AvatarButtonProps } from './types';

  // Prevent tree-shaking
  const templateClasses = getAvatarTemplateClasses();

  let {
    size = 'medium',
    variant = 'circle',
    color = 'neutral',
    icon: Icon,
    imgProps,
    children,
    href,
    target,
    rel,
    onClick,
    isSelected,
    onBlur,
    onFocus,
    onMouseLeave,
    onMouseMove,
    onMouseDown,
    onPointerDown,
    onPointerEnter,
    onTouchStart,
    onTouchEnd,
  }: AvatarButtonProps = $props();

  const isLink = $derived(Boolean(href));
  const isInteractive = $derived(Boolean(onClick || isLink));
  const elementTag = $derived(isInteractive ? (isLink ? 'a' : 'button') : 'div');
  const defaultRel = $derived(target === '_blank' ? 'noreferrer noopener' : undefined);

  // Color tokens for icon and text
  const iconColorToken = $derived(
    getButtonTextColorToken({
      property: 'icon',
      variant: 'secondary',
      color,
      state: 'default',
    }) as IconColor,
  );

  const textColorToken = $derived(
    getButtonTextColorToken({
      property: 'text',
      variant: 'secondary',
      color,
      state: 'default',
    }) as TextColors,
  );

  // Icon size
  const iconSize = $derived(avatarIconSizeTokens[size]);

  // Text size
  const textSize = $derived(avatarTextSizeMapping[size]);

  // CSS classes
  const btnClasses = $derived(
    getAvatarButtonClasses({
      size,
      variant,
      color,
      isInteractive,
      isSelected: isSelected ?? false,
    }),
  );

  // Accessibility
  const a11yAttrs = $derived(
    makeAccessible({
      role: (isInteractive ? (isLink ? 'link' : 'button') : 'presentation') as AriaRoles,
    }),
  );

  // Event handlers
  function handleClick(event: MouseEvent): void {
    if (onClick) {
      onClick(event);
    }
  }

  function handleBlur(event: FocusEvent): void {
    onBlur?.(event);
  }

  function handleFocus(event: FocusEvent): void {
    onFocus?.(event);
  }

  function handleMouseLeave(event: MouseEvent): void {
    onMouseLeave?.(event);
  }

  function handleMouseMove(event: MouseEvent): void {
    onMouseMove?.(event);
  }

  function handleMouseDown(event: MouseEvent): void {
    onMouseDown?.(event);
  }

  function handlePointerDown(event: PointerEvent): void {
    onPointerDown?.(event);
  }

  function handlePointerEnter(event: PointerEvent): void {
    onPointerEnter?.(event);
  }

  function handleTouchStart(event: TouchEvent): void {
    onTouchStart?.(event);
  }

  function handleTouchEnd(event: TouchEvent): void {
    onTouchEnd?.(event);
  }
</script>

<svelte:element
  this={elementTag}
  class={btnClasses}
  href={isLink ? href : undefined}
  target={isLink ? target : undefined}
  rel={isLink ? (rel ?? defaultRel) : undefined}
  {...a11yAttrs}
  onclick={handleClick}
  onblur={handleBlur}
  onfocus={handleFocus}
  onmouseleave={handleMouseLeave}
  onmousemove={handleMouseMove}
  onmousedown={handleMouseDown}
  onpointerdown={handlePointerDown}
  onpointerenter={handlePointerEnter}
  ontouchstart={handleTouchStart}
  ontouchend={handleTouchEnd}
>
  <div class={templateClasses.btnContent}>
    {#if Icon}
      <Icon size={iconSize} color={iconColorToken} />
    {/if}

    {#if imgProps?.src}
      <img
        src={imgProps.src}
        alt={imgProps.alt}
        srcset={imgProps.srcSet}
        crossorigin={imgProps.crossOrigin}
        referrerpolicy={imgProps.referrerPolicy}
      />
    {/if}

    {#if children}
      {#if size === 'xlarge'}
        <Heading size="medium" weight="semibold" color={textColorToken}>
          {children}
        </Heading>
      {:else}
        <BaseText
          as="span"
          color={textColorToken}
          fontSize={textSize === 'xsmall' ? 75 : textSize === 'small' ? 100 : 200}
          lineHeight={textSize === 'xsmall' ? 75 : textSize === 'small' ? 100 : 200}
          fontFamily="text"
          fontWeight="semibold"
        >
          {children}
        </BaseText>
      {/if}
    {/if}
  </div>
</svelte:element>
