// packages/blade/src/components/Collapsible/CollapsibleButton.tsx
import { forwardRef, useCallback } from 'react';

import BaseButton from '~components/Button/BaseButton';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';
import { isReactNative } from '~utils';
import { makeAnalyticsAttribute } from '~utils/makeAnalyticsAttribute';

import { useCollapsible } from './CollapsibleContext';
import { componentIds } from './componentIds';

import type { ReactElement } from 'react';
import type { ButtonProps } from '~components/Button';
import type { IconComponent } from '~components/Icons';
import type { BladeElementRef, DataAnalyticsAttribute } from '~utils/types';

type CollapsibleButtonProps = Pick<
  ButtonProps,
  | 'variant'
  | 'size'
  | 'iconPosition'
  | 'isDisabled'
  | 'testID'
  | 'accessibilityLabel'
  | 'icon'
  | 'children'
> &
  DataAnalyticsAttribute;

const _CollapsibleButton: React.ForwardRefRenderFunction<
  BladeElementRef,
  CollapsibleButtonProps
> = (
  { children, variant, size, icon, iconPosition, isDisabled, testID, accessibilityLabel, ...rest },
  ref,
): ReactElement => {
  const { onExpandChange, isExpanded, collapsibleBodyId } = useCollapsible();

  const toggleIsExpanded = useCallback(() => onExpandChange(!isExpanded), [
    onExpandChange,
    isExpanded,
  ]);

  return (
    <BaseButton
      variant={variant}
      size={size}
      // Button handles case of icon and children so we don't care about icon type safety here
      icon={icon as IconComponent}
      iconPosition={iconPosition}
      isDisabled={isDisabled}
      testID={testID}
      ref={ref}
      onClick={toggleIsExpanded}
      alignSelf={isReactNative() ? 'flex-start' : undefined}
      accessibilityProps={{
        label: accessibilityLabel,
        controls: collapsibleBodyId,
        expanded: isExpanded,
      }}
      {...makeAnalyticsAttribute(rest)}
    >
      {children}
    </BaseButton>
  );
};

const CollapsibleButton = assignWithoutSideEffects(forwardRef(_CollapsibleButton), {
  displayName: 'CollapsibleButton',
  componentId: componentIds.CollapsibleButton,
});

export type { CollapsibleButtonProps };
export { CollapsibleButton };

// packages/blade-svelte/src/components/Collapsible/CollapsibleButton.svelte
<script lang="ts">
  import Button from '../Button/Button.svelte';
  import { makeAnalyticsAttribute } from '@razorpay/blade-core/utils';
  import { getCollapsibleContext } from './context';
  import type { CollapsibleButtonProps } from './types';

  let {
    children,
    variant,
    size,
    icon,
    iconPosition,
    isDisabled,
    testID,
    accessibilityLabel,
    ...rest
  }: CollapsibleButtonProps = $props();

  const getCtx = getCollapsibleContext();

  if (!getCtx) {
    throw new Error(
      '[blade-svelte] CollapsibleButton must be used inside a <Collapsible> component.',
    );
  }

  const ctx = $derived(getCtx());
  const isExpanded = $derived(ctx.isExpanded);

  const toggleIsExpanded = () => {
    ctx.onExpandChange(!isExpanded);
  };

  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
</script>

<Button
  {variant}
  {size}
  {icon}
  {iconPosition}
  {isDisabled}
  {testID}
  {accessibilityLabel}
  aria-controls={ctx.collapsibleBodyId}
  aria-expanded={isExpanded}
  onClick={toggleIsExpanded}
  {...analyticsAttrs}
>
  {#if typeof children === 'string'}
    {children}
  {:else if children}
    {@render children()}
  {/if}
</Button>
