// packages/blade/src/components/Typography/Heading/Heading.tsx
/* eslint-disable @typescript-eslint/no-unnecessary-type-assertion */
import type { ReactElement } from 'react';
import { BaseText } from '../BaseText';
import type { BaseTextProps, BaseTextSizes } from '../BaseText/types';
import { useValidateAsProp } from '../utils';
import type { ColorContrast, ColorContrastTypes, TextTypes } from '~tokens/theme/theme';
import { getStyledProps } from '~components/Box/styledProps';
import type { StyledPropsBlade } from '~components/Box/styledProps';
import { isReactNative } from '~utils';
import type { TestID } from '~utils/types';

const validAsValues = ['span', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'] as const;
export type HeadingProps = {
  as?: typeof validAsValues[number];
  /**
   * Overrides the color of the Heading component.
   *
   * **Note** This takes priority over `type` and `contrast` prop to decide color of heading
   */
  color?: BaseTextProps['color'];
  type?: TextTypes;
  weight?: Extract<BaseTextProps['fontWeight'], 'regular' | 'semibold'>;
  contrast?: ColorContrastTypes;
  children: React.ReactNode;
  textAlign?: BaseTextProps['textAlign'];
  textDecorationLine?: BaseTextProps['textDecorationLine'];
  size?: Extract<BaseTextSizes, 'small' | 'medium' | 'large' | 'xlarge' | '2xlarge'>;
} & TestID &
  StyledPropsBlade;

const getProps = ({
  as,
  size,
  type,
  weight,
  contrast,
  color,
  testID,
}: Pick<HeadingProps, 'as' | 'size' | 'type' | 'weight' | 'contrast' | 'color' | 'testID'>): Omit<
  BaseTextProps,
  'children'
> => {
  const colorContrast: keyof ColorContrast = contrast ? `${contrast!}Contrast` : 'lowContrast';
  const props: Omit<BaseTextProps, 'children'> = {
    color: color ?? `surface.text.${type ?? 'normal'}.${colorContrast}`,
    fontSize: 300,
    fontWeight: weight ?? 'semibold',
    fontStyle: 'normal',
    lineHeight: 300,
    fontFamily: 'text',
    accessibilityProps: isReactNative() ? { role: 'heading' } : {},
    componentName: 'heading',
    testID,
  };

  if (size === 'small') {
    props.fontSize = 300;
    props.lineHeight = 300;
    props.as = 'h6';
  } else if (size === 'medium') {
    props.fontSize = 400;
    props.lineHeight = 400;
    props.as = 'h5';
  } else if (size === 'large') {
    props.fontSize = 500;
    props.lineHeight = 500;
    props.as = 'h4';
  } else if (size === 'xlarge') {
    props.fontSize = 600;
    props.lineHeight = 600;
    props.as = 'h3';
  } else if (size === '2xlarge') {
    props.fontSize = 700;
    props.lineHeight = 700;
    props.as = 'h2';
  }

  // override the computed `as` prop if user passed an `as` prop
  props.as = as || props.as;
  return props;
};

export const Heading = ({
  as,
  size = 'small',
  type = 'normal',
  weight = 'semibold',
  contrast = 'low',
  color,
  children,
  testID,
  textAlign,
  textDecorationLine,
  ...styledProps
}: HeadingProps): ReactElement => {
  useValidateAsProp({ componentName: 'Heading', as, validAsValues });

  const props = getProps({ as, size, type, weight, color, contrast, testID });

  return (
    <BaseText
      {...props}
      textAlign={textAlign}
      textDecorationLine={textDecorationLine}
      {...getStyledProps(styledProps)}
    >
      {children}
    </BaseText>
  );
};

// packages/blade-svelte/src/components/Typography/Heading/Heading.svelte
<script lang="ts">
  import BaseText from '../BaseText/BaseText.svelte';
  import type { HeadingProps } from './types';
  import { getHeadingProps, validAsValues } from './utils';
  import { getStyledProps } from '../../../utils/styledProps';

  let {
    as,
    size,
    weight,
    color,
    children,
    testID,
    textAlign,
    textDecorationLine,
    wordBreak,
    textTransform,
    ...styledProps
  }: HeadingProps = $props();

  // Set defaults
  const finalSize = (size ?? 'small') as 'small' | 'medium' | 'large' | 'xlarge' | '2xlarge';
  const finalWeight = (weight ?? 'semibold') as 'regular' | 'medium' | 'semibold';
  const finalColor = color ?? 'surface.text.gray.normal';

  // Validate as prop in development
  $effect(() => {
    if (typeof window !== 'undefined' && window.location.hostname === 'localhost') {
      if (as && !validAsValues.includes(as)) {
        console.error(
          `[Blade: Heading]: Invalid \`as\` prop value - ${as}. Only ${validAsValues.join(', ')} are accepted`,
        );
      }
    }
  });

  // Get BaseText props from Heading props
  const baseTextProps = $derived(
    getHeadingProps({
      as,
      size: finalSize,
      weight: finalWeight,
      color: finalColor,
      testID,
    }),
  );

  // Extract styled props
  const extractedStyledProps = $derived(getStyledProps(styledProps));

  // Merge props: baseTextProps first, then direct props, then styled props (matching React implementation)
  const mergedProps = $derived({
    ...baseTextProps,
    textAlign,
    textDecorationLine,
    textTransform,
    wordBreak,
    ...extractedStyledProps,
  });
</script>

<BaseText {...mergedProps}>
  {@render children()}
</BaseText>
