// packages/blade/src/components/Form/FormHint.tsx
/* eslint-disable react/display-name */
import type { ReactElement } from 'react';
import React from 'react';
import type { TextProps } from '../../../components';
import { FormHintWrapper } from './FormHintWrapper';
import { Text } from '~components/Typography/Text';
import BaseBox from '~components/Box/BaseBox';
import { CheckIcon, InfoIcon } from '~components/Icons';
import { getPlatformType } from '~utils/getPlatformType';

type HintTextProps = {
  icon?: React.ElementType;
  children: string;
  id?: string;
  color: TextProps<{ variant: 'caption' }>['color'];
};

const HintText = ({ icon: Icon, children, id, color }: HintTextProps): ReactElement => {
  const isReactNative = getPlatformType() === 'react-native';

  return (
    <BaseBox marginTop="spacing.2" id={id}>
      <FormHintWrapper>
        {Icon ? <Icon /> : null}
        <Text as={isReactNative ? undefined : 'span'} color={color} size="medium" variant="caption">
          {children}
        </Text>
      </FormHintWrapper>
    </BaseBox>
  );
};

export type FormHintProps = {
  type: 'help' | 'error' | 'success';
  /**
   * Help text for the group
   */
  helpText?: string;
  /**
   * Error text for the group
   *
   * Renders when `state` is set to 'error'
   */
  errorText?: string;
  /**
   * Success text for the group
   *
   * Renders when `state` is set to 'success'
   */
  successText?: string;
  /**
   * Sets the id on errorText.
   * Needed for accessibility reasons.
   */
  errorTextId?: string;
  /**
   * Sets the id on helpText.
   * Needed for accessibility reasons.
   */
  helpTextId?: string;
  /**
   * Sets the id on successText.
   * Needed for accessibility reasons.
   */
  successTextId?: string;
};

const Icons = {
  error: (): ReactElement => (
    <>
      <InfoIcon color="feedback.icon.negative.intense" size="small" />
      <BaseBox marginRight="spacing.2" />
    </>
  ),
  success: (): ReactElement => (
    <>
      <CheckIcon color="feedback.icon.positive.intense" size="small" />
      <BaseBox marginRight="spacing.2" />
    </>
  ),
};

const FormHint = ({
  type,
  helpText,
  errorText,
  successText,
  helpTextId,
  errorTextId,
  successTextId,
}: FormHintProps): React.ReactElement => {
  const colors: Record<string, TextProps<{ variant: 'caption' }>['color']> = {
    help: 'surface.text.gray.muted',
    error: 'feedback.text.negative.intense',
    success: 'feedback.text.positive.intense',
  };

  const showError = type === 'error' && errorText;
  const showSuccess = type === 'success' && successText;
  const showHelp = !showError && !showSuccess && helpText;

  return (
    <>
      {showHelp && (
        <HintText id={helpTextId} color={colors.help}>
          {helpText}
        </HintText>
      )}

      {showError && (
        <HintText id={errorTextId} icon={Icons.error} color={colors.error}>
          {errorText}
        </HintText>
      )}

      {showSuccess && (
        <HintText id={successTextId} icon={Icons.success} color={colors.success}>
          {successText}
        </HintText>
      )}
    </>
  );
};

export { FormHint };

// packages/blade-svelte/src/components/Form/FormHint/FormHint.svelte
<script lang="ts">
  import type { FormHintProps } from './types';
  import Text from '../../Typography/Text/Text.svelte';
  import { InfoIcon, CheckIcon } from '../../Icons';
  import {
    hintTextSize,
    hintIconSize,
    getFormHintClasses,
    getHintIconClasses,
  } from '@razorpay/blade-core/styles';

  let {
    type,
    helpText,
    errorText,
    successText,
    helpTextId,
    errorTextId,
    successTextId,
    size = 'medium',
  }: FormHintProps = $props();

  // Text sizes based on size prop
  const textSize = $derived(hintTextSize[size] as 'small' | 'medium');
  const iconSize = $derived(hintIconSize[size] as 'small' | 'medium');

  // Determine what to show
  const showError = $derived(type === 'error' && errorText);
  const showSuccess = $derived(type === 'success' && successText);
  const showHelp = $derived(!showError && !showSuccess && helpText);

  // CSS classes
  const hintClasses = $derived(getFormHintClasses({ size }));
  const iconClasses = getHintIconClasses();

  // Color mappings
  const colors = {
    help: 'surface.text.gray.muted',
    error: 'feedback.text.negative.intense',
    success: 'feedback.text.positive.intense',
  } as const;
</script>

{#if showHelp}
  <div class={hintClasses} id={helpTextId}>
    <Text
      variant="caption"
      size={textSize}
      weight="regular"
      color={colors.help}
    >
      {helpText}
    </Text>
  </div>
{/if}

{#if showError}
  <div class={hintClasses} id={errorTextId}>
    <div class={iconClasses}>
      <InfoIcon
        size={iconSize}
        color="feedback.icon.negative.intense"
      />
    </div>
    <Text
      variant="caption"
      size={textSize}
      weight="regular"
      color={colors.error}
    >
      {errorText}
    </Text>
  </div>
{/if}

{#if showSuccess}
  <div class={hintClasses} id={successTextId}>
    <div class={iconClasses}>
      <CheckIcon
        size={iconSize}
        color="feedback.icon.positive.intense"
      />
    </div>
    <Text
      variant="caption"
      size={textSize}
      weight="regular"
      color={colors.success}
    >
      {successText}
    </Text>
  </div>
{/if}
