// packages/blade-svelte/src/components/Chip/ChipGroup.svelte
<script lang="ts">
  import {
    metaAttribute,
    MetaConstants,
    makeAccessible,
    getStyledPropsClasses,
    makeAnalyticsAttribute,
  } from '@razorpay/blade-core/utils';
  import {
    getChipGroupFieldClasses,
    getChipGroupGapClasses,
    getChipGroupTemplateClasses,
    getChipGroupLabelSizeClass,
  } from '@razorpay/blade-core/styles';
  import { setChipGroupContext } from './chipContext';
  import type { ChipGroupProps, ChipGroupContextType, State } from './types';

  const templateClasses = getChipGroupTemplateClasses();

  let {
    children,
    label,
    accessibilityLabel,
    labelPosition = 'top',
    helpText,
    errorText,
    validationState = 'none',
    necessityIndicator = 'none',
    isDisabled = false,
    isRequired = false,
    name,
    defaultValue,
    value: controlledValue,
    onChange,
    selectionType = 'single',
    size = 'small',
    color = 'primary',
    testID,
    ...rest
  }: ChipGroupProps = $props();

  // ID generation
  let idCounter = 0;
  const idBase = `chip-group-${++idCounter}-${Math.random().toString(36).slice(2, 6)}`;
  const labelId = `${idBase}-label`;
  const fallbackName = name ?? idBase;

  // Selection state
  const initialValue = (() => {
    if (controlledValue !== undefined) {
      return Array.isArray(controlledValue) ? controlledValue : [controlledValue];
    }
    if (defaultValue !== undefined) {
      return Array.isArray(defaultValue) ? defaultValue : [defaultValue];
    }
    return [];
  })();

  let checkedValues = $state<string[]>(initialValue);

  // Sync controlled value
  $effect(() => {
    if (controlledValue !== undefined) {
      checkedValues = Array.isArray(controlledValue) ? controlledValue : [controlledValue];
    }
  });

  const chipState: State = {
    get value() {
      return checkedValues;
    },
    isChecked(val: string): boolean {
      if (selectionType === 'single') {
        if (val === undefined || checkedValues === undefined) return false;
        return checkedValues[0] === val;
      }
      return checkedValues.includes(val);
    },
    addValue(val: string) {
      if (isDisabled) return;
      if (selectionType === 'single') {
        checkedValues = [val];
      } else if (!checkedValues.includes(val)) {
        checkedValues = [...checkedValues, val];
      }
      onChange?.({ values: checkedValues, name: fallbackName });
    },
    removeValue(val: string) {
      if (isDisabled) return;
      if (selectionType === 'single') {
        checkedValues = [];
      } else if (checkedValues.includes(val)) {
        checkedValues = checkedValues.filter((v) => v !== val);
      }
      onChange?.({ values: checkedValues, name: fallbackName });
    },
  };

  const contextValue: ChipGroupContextType = {
    isDisabled,
    isRequired,
    necessityIndicator,
    validationState,
    name: fallbackName,
    size,
    color,
    selectionType,
    state: chipState,
  };

  setChipGroupContext(() => contextValue);

  const showError = $derived(validationState === 'error' && errorText);
  const showHelpText = $derived(!showError && helpText);

  const fieldClasses = $derived(getChipGroupFieldClasses({ labelPosition }));
  const gapClasses = $derived(getChipGroupGapClasses({ size }));
  const labelSizeClass = $derived(getChipGroupLabelSizeClass(size));

  const styledProps = $derived(getStyledPropsClasses(rest));
  const combinedWrapperClasses = $derived(
    [...(styledProps.classes || [])].filter(Boolean).join(' ') || undefined,
  );

  const groupRole = $derived(selectionType === 'single' ? 'radiogroup' : 'group');
  const metaAttrs = metaAttribute({ name: MetaConstants.ChipGroup, testID });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
  const a11yAttrs = $derived(
    makeAccessible({
      role: groupRole,
      labelledBy: label ? labelId : undefined,
      label: !label ? accessibilityLabel : undefined,
    }),
  );

  const necessityClass = $derived.by(() => {
    if (necessityIndicator === 'required') return templateClasses.necessityRequired;
    if (necessityIndicator === 'optional') return templateClasses.necessityOptional;
    return '';
  });
</script>

<div class={combinedWrapperClasses} {...metaAttrs} {...analyticsAttrs}>
  <div class={fieldClasses} {...a11yAttrs}>
    {#if label}
      <span
        id={labelId}
        class={[templateClasses.groupLabel, labelSizeClass, necessityClass]
          .filter(Boolean)
          .join(' ')}
      >
        {label}
        {#if accessibilityLabel}
          <span class={templateClasses.srOnly}>, {accessibilityLabel}</span>
        {/if}
      </span>
    {:else if accessibilityLabel}
      <span class={templateClasses.srOnly}>{accessibilityLabel}</span>
    {/if}
    <div>
      <div class={gapClasses}>
        {@render children()}
      </div>
      {#if showError}
        <span class={templateClasses.errorText}>{errorText}</span>
      {:else if showHelpText}
        <span class={templateClasses.helpText}>{helpText}</span>
      {/if}
    </div>
  </div>
</div>

// packages/blade/src/components/Chip/ChipGroup.tsx
import React from 'react';
import { chipGroupLabelSizeTokens } from './chipTokens';
import { ChipGroupProvider } from './ChipGroupContext';
import { useChipGroup } from './useChipGroup';
import type { ChipGroupProps } from './types';
import BaseBox from '~components/Box/BaseBox';
import { FormHint, FormLabel } from '~components/Form';
import { SelectorGroupField } from '~components/Form/Selector/SelectorGroupField';
import { getStyledProps } from '~components/Box/styledProps';
import { VisuallyHidden } from '~components/VisuallyHidden';
import { Text } from '~components/Typography';
import type { BladeElementRef } from '~utils/types';
import { throwBladeError } from '~utils/logger';
import { makeAnalyticsAttribute } from '~utils/makeAnalyticsAttribute';

const _ChipGroup = (
  {
    accessibilityLabel,
    label,
    labelPosition = 'top',
    necessityIndicator = 'none',
    validationState = 'none',
    errorText,
    helpText,
    isRequired = false,
    children,
    isDisabled = false,
    name,
    defaultValue,
    onChange,
    value,
    size = 'small',
    color = 'primary',
    testID,
    selectionType = 'single',
    ...rest
  }: ChipGroupProps,
  ref: React.Ref<BladeElementRef>,
): React.ReactElement => {
  const { contextValue, ids } = useChipGroup({
    defaultValue,
    onChange,
    value,
    isDisabled,
    name,
    size,
    color,
    selectionType,
    isRequired,
    validationState,
    necessityIndicator,
  });
  const showError = validationState === 'error' && errorText;
  const showHelpText = !showError && helpText;
  const accessibilityText = `${showError ? errorText : ''} ${showHelpText ? helpText : ''}`.trim();

  if (__DEV__) {
    if (selectionType === 'single' && Array.isArray(defaultValue)) {
      throwBladeError({
        moduleName: 'ChipGroup',
        message: `When "selectionType" is "single", the "defaultValue" prop must be a string value, but an array was provided.`,
      });
    }
    if (selectionType === 'single' && Array.isArray(value)) {
      throwBladeError({
        moduleName: 'ChipGroup',
        message: `When "selectionType" is "single", the "value" prop must be a string value, but an array was provided.`,
      });
    }
  }

  return (
    <ChipGroupProvider value={contextValue}>
      <BaseBox ref={ref as never} {...getStyledProps(rest)}>
        <SelectorGroupField
          position={labelPosition}
          accessibilityRole={selectionType === 'single' ? 'radiogroup' : 'group'}
          labelledBy={ids.labelId}
          componentName="chip-group"
          testID={testID}
          {...makeAnalyticsAttribute(rest)}
        >
          {label ? (
            <FormLabel
              as="span"
              necessityIndicator={necessityIndicator}
              position={labelPosition}
              id={ids.labelId}
              accessibilityText={accessibilityText && `,${accessibilityText}`}
              size={chipGroupLabelSizeTokens[size]}
            >
              {label}
            </FormLabel>
          ) : null}
          <BaseBox>
            <VisuallyHidden>
              <Text>{accessibilityLabel}</Text>
            </VisuallyHidden>
            <BaseBox display="flex" flexDirection="row" flexWrap="wrap">
              {React.Children.map(children, (child) => child)}
            </BaseBox>
            <FormHint
              size={chipGroupLabelSizeTokens[size]}
              type={validationState === 'error' ? 'error' : 'help'}
              errorText={errorText}
              helpText={helpText}
            />
          </BaseBox>
        </SelectorGroupField>
      </BaseBox>
    </ChipGroupProvider>
  );
};

const ChipGroup = React.forwardRef(_ChipGroup);

export { ChipGroup };
export type { ChipGroupProps };
