// packages/blade-svelte/src/components/Chip/Chip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import {
    metaAttribute,
    MetaConstants,
    getStyledPropsClasses,
    makeAnalyticsAttribute,
  } from '@razorpay/blade-core/utils';
  import {
    getChipTemplateClasses,
    getChipWrapperClasses,
    getChipAnimatedClasses,
    getChipTextColorClass,
    getChipTextSizeClass,
  } from '@razorpay/blade-core/styles';
  import type { ChipProps, ChipColor } from './types';
  import { getChipGroupContext } from './chipContext';

  // Prevent tree-shaking
  const cls = getChipTemplateClasses();

  let {
    children,
    icon: Icon,
    color,
    isDisabled,
    value,
    width,
    maxWidth,
    minWidth,
    testID,
    ...rest
  }: ChipProps = $props();

  // Read context from ChipGroup (returns a getter function for reactivity)
  const getGroupProps = getChipGroupContext();

  // Derive reactive group props by calling the getter inside $derived
  const groupProps = $derived(getGroupProps());

  const isInsideGroup = $derived(Object.keys(groupProps).length > 0);

  $effect(() => {
    if (!isInsideGroup && typeof window !== 'undefined') {
      console.error(
        '[Blade: Chip] <Chip /> component should only be used within the context of a <ChipGroup /> component',
      );
    }
  });

  // Derive effective props from group context
  const _isDisabled = $derived(isDisabled ?? groupProps?.isDisabled ?? false);
  const _size = $derived(groupProps?.size ?? 'small');
  const chipColor = $derived<ChipColor>((color ?? groupProps?.color ?? 'primary') as ChipColor);
  const _isChecked = $derived(groupProps?.state?.isChecked(value!) ?? false);
  const _name = $derived(groupProps?.name);
  const selectionType = $derived(groupProps?.selectionType ?? 'single');
  const _isRequired = $derived(
    groupProps?.isRequired || groupProps?.necessityIndicator === 'required',
  );
  const hasError = $derived(groupProps?.validationState === 'error');
  const hasIcon = $derived(Boolean(Icon));

  // Press animation state
  let isPressed = $state(false);

  // Handlers for press animation
  function handlePointerDown() {
    if (_isDisabled) return;
    isPressed = true;
  }

  function handlePointerUp() {
    if (_isDisabled) return;
    isPressed = false;
  }

  function handlePointerOut() {
    if (_isDisabled) return;
    isPressed = false;
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (_isDisabled) return;
    if (e.key === ' ') {
      isPressed = true;
    }
  }

  function handleKeyUp(e: KeyboardEvent) {
    if (_isDisabled) return;
    if (e.key === ' ') {
      isPressed = false;
    }
  }

  // Handle input change (native radio/checkbox behavior)
  function handleChange() {
    if (_isDisabled) return;
    const currentGroupProps = getGroupProps();
    if (_isChecked) {
      currentGroupProps?.state?.removeValue(value!);
    } else {
      currentGroupProps?.state?.addValue(value!);
    }
  }

  // Computed classes
  const wrapperClasses = $derived(
    getChipWrapperClasses({
      size: _size,
      hasIcon,
      isChecked: _isChecked,
      isDisabled: _isDisabled,
      chipColor,
    }),
  );

  const animatedClasses = $derived(
    getChipAnimatedClasses({
      size: _size,
      isPressed,
      isChecked: _isChecked,
      isDisabled: _isDisabled,
      chipColor,
    }),
  );

  const textColorClass = $derived(
    getChipTextColorClass({
      isChecked: _isChecked,
      isDisabled: _isDisabled,
      chipColor,
    }),
  );

  const textSizeClass = $derived(getChipTextSizeClass(_size));

  // Styled props
  const styledProps = $derived(getStyledPropsClasses(rest));
  const outerClasses = $derived(
    [cls.chipOuter, ...(styledProps.classes || [])].filter(Boolean).join(' '),
  );

  // Meta & analytics attributes
  const metaAttrs = metaAttribute({ name: MetaConstants.Chip, testID });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));

  // Input type based on selection type
  const inputType = $derived(selectionType === 'single' ? 'radio' : 'checkbox');

  // Children handling
  const isStringChildren = $derived(typeof children === 'string');
  const snippetChildren = $derived(
    !isStringChildren && children ? (children as Snippet) : undefined,
  );

  // Outer element style for width/maxWidth/minWidth
  const outerStyle = $derived.by(() => {
    const parts: string[] = [];
    if (width) parts.push(`width: ${width}`);
    if (maxWidth) parts.push(`max-width: ${maxWidth}`);
    if (minWidth) parts.push(`min-width: ${minWidth}`);
    return parts.length > 0 ? parts.join('; ') : undefined;
  });
</script>

<div
  class={outerClasses}
  style={outerStyle}
  {...metaAttrs}
  {...analyticsAttrs}
>
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <label
    class={cls.chipLabel}
    data-disabled={_isDisabled ? 'true' : undefined}
    {...metaAttribute({ name: MetaConstants.ChipLabel })}
    onmousedown={handlePointerDown}
    onmouseup={handlePointerUp}
    onmouseout={handlePointerOut}
    ontouchstart={handlePointerDown}
    ontouchend={handlePointerUp}
    onkeydown={handleKeyDown}
    onkeyup={handleKeyUp}
  >
    <div style="display: flex; flex-direction: column; width: 100%;">
      <div style="display: flex; align-items: center; flex-direction: row;">
        <input
          class={cls.hiddenInput}
          type={inputType}
          name={_name}
          {value}
          checked={_isChecked}
          disabled={_isDisabled || undefined}
          required={_isRequired || undefined}
          aria-invalid={hasError || undefined}
          onchange={handleChange}
        />
        <div class={animatedClasses}>
          <div class={wrapperClasses}>
            {#if Icon}
              <span class={cls.chipIconWrapper}>
                <!-- TODO: Render Icon component when Icons are migrated -->
              </span>
            {/if}
            {#if isStringChildren}
              <span class="{cls.chipText} {textColorClass} {textSizeClass}">
                {children}
              </span>
            {:else if snippetChildren}
              <span class="{cls.chipText} {textColorClass} {textSizeClass}">
                {@render snippetChildren()}
              </span>
            {/if}
          </div>
        </div>
      </div>
    </div>
  </label>
</div>

// packages/blade/src/components/Chip/Chip.tsx
import React from 'react';
import { useChipGroupContext } from './ChipGroupContext';
import {
  chipIconSizes,
  chipTextSizes,
  chipColorTokens,
  getChipInputHoverTokens,
  chipHeightTokens,
  chipHorizontalPaddingTokens,
} from './chipTokens';
import type { ChipProps } from './types';
import { AnimatedChip } from './AnimatedChip';
import { StyledChipWrapper } from './StyledChipWrapper';
import isEmpty from '~utils/lodashButBetter/isEmpty';
import { metaAttribute, MetaConstants } from '~utils/metaAttribute';
import { getStyledProps } from '~components/Box/styledProps';
import BaseBox from '~components/Box/BaseBox';
import { SelectorLabel } from '~components/Form/Selector/SelectorLabel';
import { SelectorInput } from '~components/Form/Selector/SelectorInput';
import type { BladeElementRef } from '~utils/types';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';
import { throwBladeError } from '~utils/logger';
import { useCheckbox } from '~components/Checkbox/useCheckbox';
import { useRadio } from '~components/Radio/useRadio';
import { isReactNative, makeSize, useBreakpoint } from '~utils';
import { Text } from '~components/Typography';
import { useTheme } from '~components/BladeProvider';
import { getInnerMotionRef, getOuterMotionRef } from '~utils/getMotionRefs';
import { makeAnalyticsAttribute } from '~utils/makeAnalyticsAttribute';

type OnChange = ({
  isChecked,
  event,
  value,
}: {
  isChecked: boolean;
  event?: React.ChangeEvent;
  value?: string;
}) => void;

const _Chip: React.ForwardRefRenderFunction<BladeElementRef, ChipProps> = (
  {
    isDisabled,
    value,
    children,
    icon: Icon,
    color,
    testID,
    _motionMeta,
    width,
    maxWidth,
    minWidth,
    ...rest
  },
  ref,
) => {
  const { theme } = useTheme();
  const { matchedDeviceType } = useBreakpoint({ breakpoints: theme.breakpoints });
  const groupProps = useChipGroupContext();
  const isInsideGroup = !isEmpty(groupProps);
  const [isPressed, setIsPressed] = React.useState(false);

  if (__DEV__) {
    if (!isInsideGroup) {
      throwBladeError({
        moduleName: 'Chip',
        message:
          '<Chip /> component should only be used within the context of a <ChipGroup /> component',
      });
    }
  }

  const hasError = groupProps?.validationState === 'error';
  const _isDisabled = isDisabled ?? groupProps?.isDisabled;
  const _isRequired = groupProps?.isRequired || groupProps?.necessityIndicator === 'required';
  const _name = groupProps?.name;
  // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
  const _isChecked = groupProps?.state?.isChecked(value!);
  // Check if the defaultValue property of groupProps is undefined
  const defaultChecked =
    typeof groupProps?.defaultValue === 'undefined'
      ? undefined // If undefined, defaultChecked is also undefined
      : groupProps?.defaultValue?.includes(value as string); // If multiple selection, check if value is in defaultValue array
  const useChip = groupProps?.selectionType === 'single' ? useRadio : useCheckbox;
  const _size = groupProps?.size || 'small';
  const chipColor = color ?? groupProps?.color ?? 'primary';

  const handleChange: OnChange = ({ isChecked, value }) => {
    if (isChecked) {
      groupProps?.state?.addValue(value!);
    } else {
      groupProps?.state?.removeValue(value!);
    }
  };

  const { state, inputProps } = useChip({
    defaultChecked,
    isChecked: _isChecked,
    isDisabled: _isDisabled,
    isRequired: _isRequired,
    hasError,
    name: _name,
    value,
    onChange: handleChange,
  });

  const handlePointerPressedIn = React.useCallback(() => {
    if (_isDisabled) return;
    setIsPressed(true);
  }, [_isDisabled]);

  const handlePointerPressedOut = React.useCallback(() => {
    if (_isDisabled) return;
    setIsPressed(false);
  }, [_isDisabled]);

  const handleKeyboardPressedIn = React.useCallback(
    (e: React.KeyboardEvent) => {
      if (_isDisabled) return;
      if (e.key === ' ') {
        setIsPressed(true);
      }
    },
    [_isDisabled],
  );

  const handleKeyboardPressedOut = React.useCallback(
    (e: React.KeyboardEvent) => {
      if (_isDisabled) return;
      if (e.key === ' ') {
        setIsPressed(false);
      }
    },
    [_isDisabled],
  );

  let textVariant = 'unchecked';
  if (_isChecked && chipColor) {
    textVariant = chipColor;
  }
  if (_isDisabled) {
    textVariant = 'disabled';
  }
  const chipTextColor = chipColorTokens.text[textVariant];
  const chipIconColor = chipColorTokens.icon[textVariant];

  let colorVariant = 'unchecked';
  const stateVariant = _isDisabled ? 'disabled' : 'default';
  if (_isChecked && chipColor) {
    colorVariant = chipColor;
  }
  const chipBackgroundColor = chipColorTokens.background[colorVariant][stateVariant];
  const chipBorderColor = chipColorTokens.border[colorVariant][stateVariant];

  return (
    <BaseBox
      {...metaAttribute({ name: MetaConstants.Chip, testID })}
      {...getStyledProps(rest)}
      {...makeAnalyticsAttribute(rest)}
      display={(isReactNative() ? 'flex' : 'inline-flex') as never}
      ref={getOuterMotionRef({ _motionMeta, ref })}
    >
      <SelectorLabel
        componentName={MetaConstants.ChipLabel}
        onTouchStart={handlePointerPressedIn}
        onTouchEnd={handlePointerPressedOut}
        onMouseDown={handlePointerPressedIn}
        onMouseUp={handlePointerPressedOut}
        onMouseOut={handlePointerPressedOut}
        onKeyDown={handleKeyboardPressedIn}
        onKeyUp={handleKeyboardPressedOut}
        inputProps={isReactNative() ? inputProps : {}}
        style={{ cursor: _isDisabled ? 'not-allowed' : 'pointer' }}
      >
        <BaseBox display="flex" flexDirection="column">
          <BaseBox display="flex" alignItems="center" flexDirection="row">
            <SelectorInput
              hoverTokens={getChipInputHoverTokens(chipColor)}
              isChecked={state.isChecked}
              isDisabled={_isDisabled}
              inputProps={inputProps}
              hasError={hasError}
              ref={getInnerMotionRef({ _motionMeta, ref })}
            />
            <AnimatedChip
              borderColor={chipBorderColor}
              isDisabled={_isDisabled}
              isPressed={isPressed}
              isDesktop={matchedDeviceType === 'desktop'}
            >
              <StyledChipWrapper
                borderColor={chipBorderColor}
                isChecked={_isChecked}
                isDisabled={_isDisabled}
                color={chipColor}
                display="flex"
                flexDirection="row"
                justifyContent="center"
                alignItems="center"
                overflow="hidden"
                backgroundColor={chipBackgroundColor}
                borderRadius="max"
                borderWidth={['xsmall', 'small'].includes(_size) ? 'thinner' : 'thin'}
                paddingLeft={
                  chipHorizontalPaddingTokens[Boolean(Icon) ? 'withIcon' : 'withoutIcon'].left[
                    _size
                  ]
                }
                paddingRight={
                  chipHorizontalPaddingTokens[Boolean(Icon) ? 'withIcon' : 'withoutIcon'].right[
                    _size
                  ]
                }
                height={makeSize(chipHeightTokens[_size])}
                gap="spacing.3"
                width={width}
                maxWidth={maxWidth}
                minWidth={minWidth}
              >
                {Icon ? (
                  <BaseBox display="flex">
                    <Icon color={chipIconColor} size={chipIconSizes[_size]} />
                  </BaseBox>
                ) : null}
                {children ? (
                  <Text {...chipTextSizes[_size]} truncateAfterLines={1} color={chipTextColor}>
                    {children}
                  </Text>
                ) : null}
              </StyledChipWrapper>
            </AnimatedChip>
          </BaseBox>
        </BaseBox>
      </SelectorLabel>
    </BaseBox>
  );
};

const Chip = assignWithoutSideEffects(React.forwardRef(_Chip), {
  displayName: 'Chip',
});

export { Chip };
export type { ChipProps };
