// packages/blade-svelte/src/components/Input/TextInput/TextInput.svelte
<script lang="ts">
  import type { Snippet, Component } from 'svelte';
  import type { TextInputProps, IconComponent } from './types';
  import type { FormInputOnEvent, FormInputKeyDownEvent } from '../BaseInput/types';
  import { BaseInput } from '../BaseInput';
  import { IconButton } from '../../Button/IconButton';
  import { CloseIcon } from '../../Icons';
  import { Divider } from '../../Divider';
  import { CharacterCounter } from '../../Form';
  import Spinner from '../../Spinner/BaseSpinner/BaseSpinner.svelte';
  import { hintMarginTop } from '@razorpay/blade-core/styles';
  import { metaAttribute, MetaConstants } from '@razorpay/blade-core/utils';
  import { formatValue, stripPatternCharacters, isUserCharacter } from './useFormattedInput';
  import type { IconProps } from '../../Icons/types';

  let {
    label,
    accessibilityLabel,
    labelPosition = 'top',
    labelSuffix,
    labelTrailing,
    necessityIndicator = 'none',
    validationState = 'none',
    helpText,
    errorText,
    successText,
    placeholder,
    defaultValue,
    name,
    value = $bindable(),
    isDisabled = false,
    isRequired = false,
    prefix,
    suffix,
    maxCharacters,
    autoFocus = false,
    keyboardReturnKeyType,
    autoCompleteSuggestionType,
    autoCapitalize,
    testID,
    size = 'medium',
    leadingIcon,
    trailingIcon,
    type = 'text',
    textAlign = 'left',
    leading,
    trailing,
    showClearButton = false,
    onClearButtonClick,
    isLoading = false,
    trailingButton,
    format,
    hasPopup,
    popupId,
    isPopupExpanded,
    onChange,
    onFocus,
    onBlur,
    onClick,
    onKeyDown,
  }: TextInputProps = $props();

  // Reference to BaseInput
  let baseInputRef: BaseInput | undefined = $state();

  // Internal state for clear button visibility
  let shouldShowClearButton = $state(false);

  // Input focus state
  let isInputFocused = $state(autoFocus);

  // Formatted input state
  let formattedValue = $state('');
  let rawValue = $state('');
  let inputElement: HTMLInputElement | null = null;
  let cursorInfo: { position?: number; endOfSection?: boolean } = {};

  // Track if we're currently processing user input
  let isProcessingInput = false;

  // Initialize and sync formatted value
  // Only update when value changes from external source (not from user typing)
  $effect(() => {
    if (format && !isProcessingInput) {
      const initial = value ?? defaultValue ?? '';
      const raw = stripPatternCharacters(initial);
      const newFormatted = formatValue(raw, format);
      
      // Only update if the formatted result is different
      if (newFormatted !== formattedValue) {
        formattedValue = newFormatted;
        rawValue = raw;
      }
    }
  });

  // Update clear button visibility
  $effect(() => {
    const currentValue = format ? formattedValue : (value ?? defaultValue);
    shouldShowClearButton = Boolean(showClearButton && currentValue);
  });

  // Computed values
  const effectiveMaxCharacters = $derived(format ? format.length : maxCharacters);
  const inputValue = $derived(format ? formattedValue : value);

  // Determine leading/trailing icons from leading/trailing props
  const _leadingIcon = $derived.by(() => {
    if (leadingIcon) return leadingIcon;
    // Check if leading is an icon component (has name property typical of components)
    if (leading && typeof leading === 'function' && 'name' in leading) {
      return leading as IconComponent;
    }
    return undefined;
  });

  const _trailingIcon = $derived.by(() => {
    if (trailingIcon) return trailingIcon;
    if (trailing && typeof trailing === 'function' && 'name' in trailing) {
      return trailing as IconComponent;
    }
    return undefined;
  });

  // Check if leading/trailing are custom elements (snippets)
  const hasLeadingInteractionElement = $derived(
    !_leadingIcon && leading && typeof leading === 'function'
  );
  const hasTrailingInteractionElement = $derived(
    !_trailingIcon && trailing && typeof trailing === 'function'
  );

  // Format validation
  $effect(() => {
    if (format && typeof window !== 'undefined' && window.location.hostname === 'localhost') {
      const hasAlphanumeric = /[a-zA-Z0-9]/.test(format);
      if (hasAlphanumeric) {
        console.error(
          `[Blade: TextInput] Invalid format "${format}". Only # and special characters allowed, no letters/numbers.`
        );
      }
    }
  });

  // Handle formatted input change
  function handleFormattedChange(event: FormInputOnEvent): void {
    if (!format) {
      handleOnChange(event);
      return;
    }

    // Mark that we're processing user input to prevent effect from interfering
    isProcessingInput = true;

    const inputVal = event.value ?? '';
    const currentValue = formattedValue;
    const cursorPosition = inputElement?.selectionStart ?? 0;
    const didDelete = inputVal.length < currentValue.length;

    cursorInfo.position = cursorPosition;

    let newRawValue = stripPatternCharacters(inputVal);

    // Handle delimiter deletion
    if (didDelete) {
      const deletedChar = currentValue[cursorPosition] ?? '';
      const deletedDelimiter = !isUserCharacter(deletedChar);

      if (deletedDelimiter) {
        const beforeCursor = inputVal.substring(0, cursorPosition);
        const afterCursor = inputVal.substring(cursorPosition);
        const rawBefore = stripPatternCharacters(beforeCursor);
        const rawAfter = stripPatternCharacters(afterCursor);

        newRawValue = rawBefore.slice(0, -1) + rawAfter;
        cursorInfo.position = beforeCursor.replace(/([\d\w]+)[^\dA-Za-z]+$/, '$1').length - 1;
      }
    }

    const newFormattedValue = formatValue(newRawValue, format);
    cursorInfo.endOfSection = false;

    // Handle cursor positioning when typing
    if (!didDelete) {
      const nextChar = newFormattedValue[cursorPosition];
      const nextIsDelimiter = nextChar ? !isUserCharacter(nextChar) : false;

      const remainingText = newFormattedValue.substring(cursorPosition);
      const nextUserCharIndex = remainingText.search(/[\dA-Za-z]/);
      const hasMoreUserChars = nextUserCharIndex !== -1;

      cursorInfo.endOfSection = nextIsDelimiter && !hasMoreUserChars;

      if (nextIsDelimiter && hasMoreUserChars) {
        const prevChar = newFormattedValue[cursorPosition - 1] ?? '';
        const prevIsDelimiter = !isUserCharacter(prevChar);

        if (prevIsDelimiter) {
          cursorInfo.position = cursorPosition + nextUserCharIndex + 1;
        } else {
          const delimiterExistedBefore =
            currentValue[cursorPosition] === newFormattedValue[cursorPosition];
          if (delimiterExistedBefore) {
            cursorInfo.position = cursorPosition + 1;
          }
        }
      }
    }

    formattedValue = newFormattedValue;
    rawValue = newRawValue;

    onChange?.({ name: event.name, value: newFormattedValue, rawValue: newRawValue });

    // Apply cursor position
    if (inputElement && cursorInfo.position !== undefined && !cursorInfo.endOfSection) {
      requestAnimationFrame(() => {
        inputElement?.setSelectionRange(cursorInfo.position!, cursorInfo.position!);
      });
    }

    // Reset flag after a microtask to allow effect to run for external changes
    queueMicrotask(() => {
      isProcessingInput = false;
    });
  }

  // Event handlers
  function handleOnChange(event: FormInputOnEvent): void {
    if (showClearButton && event.value?.length) {
      shouldShowClearButton = true;
    }

    if (shouldShowClearButton && !event.value?.length) {
      shouldShowClearButton = false;
    }

    if (format) {
      handleFormattedChange(event);
    } else {
      if (value !== undefined) {
        value = event.value;
      }
      onChange?.(event);
    }
  }

  function handleOnFocus(event: FormInputOnEvent): void {
    isInputFocused = true;
    onFocus?.(event);
  }

  function handleOnBlur(event: FormInputOnEvent): void {
    isInputFocused = false;
    onBlur?.(event);
  }

  function handleOnKeyDown(event: FormInputKeyDownEvent): void {
    // Capture input element for cursor positioning
    if (format && event.event?.currentTarget) {
      inputElement = event.event.currentTarget as HTMLInputElement;
    }
    onKeyDown?.(event);
  }

  function handleClearButtonClick(): void {
    baseInputRef?.clear();
    if (format) {
      formattedValue = '';
      rawValue = '';
    }
    if (value !== undefined) {
      value = '';
    }
    onClearButtonClick?.();
    baseInputRef?.focus();
    shouldShowClearButton = false;
  }

  // Export methods
  export function focus(): void {
    baseInputRef?.focus();
  }

  export function blur(): void {
    baseInputRef?.blur();
  }

  export function clear(): void {
    handleClearButtonClick();
  }
</script>

<BaseInput
  bind:this={baseInputRef}
  id={name ?? 'textinput'}
  componentName={MetaConstants.TextInput}
  {name}
  {label}
  {accessibilityLabel}
  hideLabelText={!label}
  {labelPosition}
  {labelSuffix}
  {labelTrailing}
  {placeholder}
  {type}
  value={inputValue}
  defaultValue={format ? undefined : defaultValue}
  {isDisabled}
  isRequired={isRequired}
  {necessityIndicator}
  {validationState}
  {helpText}
  {errorText}
  {successText}
  {size}
  leadingIcon={_leadingIcon}
  trailingIcon={_trailingIcon}
  {prefix}
  {suffix}
  maxCharacters={effectiveMaxCharacters}
  {textAlign}
  {autoFocus}
  {autoCapitalize}
  {autoCompleteSuggestionType}
  {keyboardReturnKeyType}
  {hasPopup}
  {popupId}
  {isPopupExpanded}
  {trailingButton}
  {testID}
  onChange={handleOnChange}
  onFocus={handleOnFocus}
  onBlur={handleOnBlur}
  onClick={onClick}
  onKeyDown={handleOnKeyDown}
>
  {#snippet leadingInteractionElement()}
    {#if hasLeadingInteractionElement && typeof leading === 'function'}
      {@render leading()}
    {/if}
  {/snippet}

  {#snippet trailingInteractionElement()}
    {#if isLoading}
      <Spinner accessibilityLabel="Loading Content" color="primary" size="medium" />
    {:else if shouldShowClearButton && hasTrailingInteractionElement}
      <div style="display: flex; align-items: center; gap: 8px;">
        <IconButton
          icon={CloseIcon}
          size="medium"
          accessibilityLabel="Clear Input Content"
          isDisabled={isDisabled}
          onClick={handleClearButtonClick}
        />
        <Divider orientation="vertical" />
        {#if typeof trailing === 'function'}
          {@render trailing()}
        {/if}
      </div>
    {:else if shouldShowClearButton}
      <IconButton
        icon={CloseIcon}
        size="medium"
        accessibilityLabel="Clear Input Content"
        isDisabled={isDisabled}
        onClick={handleClearButtonClick}
      />
    {:else if hasTrailingInteractionElement && typeof trailing === 'function'}
      {@render trailing()}
    {/if}
  {/snippet}

  {#snippet trailingFooterSlot(currentValue)}
    {#if !format && effectiveMaxCharacters}
      <div style="margin-top: {hintMarginTop[size]}; margin-right: 4px;">
        <CharacterCounter
          currentCount={currentValue?.length ?? 0}
          maxCount={effectiveMaxCharacters}
          {size}
        />
      </div>
    {/if}
  {/snippet}
</BaseInput>

// packages/blade/src/components/Input/TextInput/TextInput.tsx
import React, { useEffect, useState, useRef } from 'react';
import type { ReactElement, ReactNode } from 'react';
import type { TextInput as TextInputReactNative } from 'react-native';
import type { BaseInputProps } from '../BaseInput';
import { BaseInput } from '../BaseInput';
import { getKeyboardAndAutocompleteProps } from '../BaseInput/utils';
import type { TaggedInputProps } from '../BaseInput/useTaggedInput';
import { useTaggedInput } from '../BaseInput/useTaggedInput';
import { useFormattedInput } from './useFormattedInput';
import isEmpty from '~utils/lodashButBetter/isEmpty';
import type { IconComponent } from '~components/Icons';
import { CloseIcon } from '~components/Icons';
import { IconButton } from '~components/Button/IconButton';
import type { StyledPropsBlade } from '~components/Box/styledProps';
import { MetaConstants } from '~utils/metaAttribute';
import { CharacterCounter } from '~components/Form/CharacterCounter';
import BaseBox from '~components/Box/BaseBox';
import { Spinner } from '~components/Spinner';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';
import { getPlatformType } from '~utils';
import { useMergeRefs } from '~utils/useMergeRefs';
import type {
  BladeElementRef,
  BladeElementRefWithValue,
  ContainerElementType,
  DataAnalyticsAttribute,
} from '~utils/types';
import { hintMarginTop } from '~components/Form/formTokens';
import { Divider } from '~components/Divider';
import { getComponentId } from '~utils/isValidAllowedChildren';
import { DropdownOverlay } from '~components/Dropdown';
import type { FormInputOnEvent } from '~components/Form/FormTypes';
import { isIconComponent } from '~utils/isIconComponent';
import { useDatePickerContext } from '~components/DatePicker/DatePickerContext';

// Users should use PasswordInput for input type password
type Type = Exclude<BaseInputProps['type'], 'password'>;

type TextInputCommonProps = Pick<
  BaseInputProps,
  | 'label'
  | 'accessibilityLabel'
  | 'labelPosition'
  | 'labelSuffix'
  | 'labelTrailing'
  | 'necessityIndicator'
  | 'validationState'
  | 'helpText'
  | 'errorText'
  | 'successText'
  | 'placeholder'
  | 'defaultValue'
  | 'name'
  | 'onChange'
  | 'onFocus'
  | 'onBlur'
  | 'value'
  | 'isDisabled'
  | 'isRequired'
  | 'prefix'
  | 'suffix'
  | 'maxCharacters'
  | 'autoFocus'
  | 'keyboardReturnKeyType'
  | 'autoCompleteSuggestionType'
  | 'onSubmit'
  | 'autoCapitalize'
  | 'testID'
  | 'onClick'
  | 'size'
  | 'leadingIcon'
  | 'trailingButton'
  | 'trailingIcon'
  | 'textAlign'
  | 'popupId'
  | 'isPopupExpanded'
  | 'hasPopup'
  | 'componentName'
  | 'onKeyDown'
  | keyof DataAnalyticsAttribute
> & {
  /**
   * Decides whether to render a clear icon button
   */
  showClearButton?: boolean;

  /**
   * Event handler to handle the onClick event for clear button. Used when `showClearButton` is `true`
   */
  onClearButtonClick?: () => void;

  /**
   * Decides whether to show a loading spinner for the input field.
   */
  isLoading?: boolean;

  /**
   * Icon that will be rendered at the beginning of the input field
   * @deprecated Use `leading` instead. This prop will be removed in the next major version.
   */
  icon?: IconComponent;
  /**
   * Type of Input Field to be rendered. Use `PasswordInput` for type `password`
   *
   *
   * **Note on number type**
   *
   * `type="number"` internally uses `inputMode="numeric"` instead of HTML's `type="number"` which also allows text characters.
   * If you have a usecase where you only want to support number input, you can handle it on validations end.
   *
   * Check out [Why the GOV.UK Design System team changed the input type for numbers](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/) for reasoning
   *
   * @default text
   */
  type?: Type;
  /**
   *
   * Icon or React Element to be rendered at the end of the input field
   */
  trailing?: React.ReactElement | IconComponent;
  /**
   * Icon or React Element to be rendered at the beginning of the input field
   */
  leading?: React.ReactElement | IconComponent;
  /**
   * Format pattern where # represents input characters and other symbols act as delimiters
   * When provided, input will be automatically formatted and onChange will include rawValue
   *
   * **Note:**
   * 1. Format pattern should only contain # symbols and special characters as delimiters.
   *    Alphanumeric characters (letters and numbers) are not allowed in the format pattern.
   * 2. When format is provided, user input is restricted to alphanumeric characters only.
   *    Special characters and symbols will be filtered out automatically from user input.
   *
   * @example "#### #### #### ####" for card numbers
   * @example "##/##" for expiry dates
   * @example "(###) ###-####" for phone numbers
   */
  format?:
    | '#### #### #### ####'
    | '##/##'
    | '##/##/####'
    | '(###) ###-####'
    | '###-##-####'
    | '##:##'
    | '##:##:##'
    | '#### #### ####'
    | '###.###.###.###'
    | '## ## ####'
    | '##-###-##'
    // eslint-disable-next-line @typescript-eslint/ban-types
    | (string & {});
} & TaggedInputProps &
  StyledPropsBlade;

/*
  Mandatory accessibilityLabel prop when label is not provided
*/
type TextInputPropsWithA11yLabel = {
  /**
   * Label to be shown for the input field
   */
  label?: undefined;
  /**
   * Accessibility label for the input
   */
  accessibilityLabel: string;
};

/*
  Optional accessibilityLabel prop when label is provided
*/
type TextInputPropsWithLabel = {
  /**
   * Label to be shown for the input field
   */
  label: string;
  /**
   * Accessibility label for the input
   */
  accessibilityLabel?: string;
};

type TextInputProps = (TextInputPropsWithA11yLabel | TextInputPropsWithLabel) &
  TextInputCommonProps;

// need to do this to tell TS to infer type as TextInput of React Native and make it believe that `ref.current.clear()` exists
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const isReactNative = (_textInputRef: any): _textInputRef is TextInputReactNative => {
  return getPlatformType() === 'react-native';
};

const _TextInput: React.ForwardRefRenderFunction<BladeElementRef, TextInputProps> = (
  {
    label,
    accessibilityLabel,
    labelPosition = 'top',
    placeholder,
    type = 'text',
    defaultValue,
    name,
    value,
    maxCharacters,
    format,
    onChange,
    onClick,
    onFocus,
    onBlur,
    onSubmit,
    isDisabled,
    necessityIndicator,
    validationState,
    errorText,
    helpText,
    successText,
    isRequired,
    icon,
    prefix,
    showClearButton,
    onClearButtonClick,
    isLoading,
    suffix,
    autoFocus,
    keyboardReturnKeyType,
    autoCompleteSuggestionType,
    autoCapitalize,
    testID,
    size = 'medium',
    leadingIcon,
    trailingIcon,
    isTaggedInput,
    tags,
    onTagChange,
    trailing,
    leading,
    labelSuffix,
    labelTrailing,
    onKeyDown,
    ...rest
  },
  ref,
): ReactElement => {
  const textInputRef = React.useRef<BladeElementRefWithValue>(null);
  const mergedRef = useMergeRefs(ref, textInputRef);
  const [shouldShowClearButton, setShouldShowClearButton] = useState(false);
  const [isInputFocussed, setIsInputFocussed] = useState(autoFocus ?? false);
  const context = useDatePickerContext();
  const isDatePickerBodyOpen = context?.isDatePickerBodyOpen;

  if (__DEV__) {
    if (format) {
      const hasAlphanumeric = /[a-zA-Z0-9]/.test(format);
      if (hasAlphanumeric) {
        throw new Error(
          `[Blade: TextInput] Invalid format "${format}". Only # and special characters allowed, no letters/numbers.`,
        );
      }
    }
  }

  const formattingResult = useFormattedInput({
    format,
    onChange,
    value,
    defaultValue,
  });

  const inputValue = format ? formattingResult.formattedValue : value;
  const effectiveMaxCharacters = format ? formattingResult.maxLength : maxCharacters;

  const handleOnChange: FormInputOnEvent = React.useCallback(
    ({ name, value: inputValue }) => {
      if (format) {
        formattingResult.handleChange({ name, value: inputValue });
      } else {
        onChange?.({ name, value: inputValue });
      }
    },
    [format, formattingResult.handleChange, onChange],
  );

  const {
    activeTagIndex,
    setActiveTagIndex,
    getTags,
    handleTaggedInputKeydown,
    handleTaggedInputChange,
    handleTagsClear,
  } = useTaggedInput({
    isTaggedInput,
    tags,
    onTagChange,
    isDisabled,
    onChange: handleOnChange,
    name,
    value: inputValue,
    inputRef: textInputRef,
  });
  const [isTrailingDropDownOpen, setIsTrailingDropDownOpen] = React.useState(false);
  const [isLeadingDropDownOpen, setIsLeadingDropDownOpen] = React.useState(false);
  const textInputWrapperRef = useRef<ContainerElementType | null>(null);

  useEffect(() => {
    if (
      (isTrailingDropDownOpen && isLeadingDropDownOpen) ||
      (isDatePickerBodyOpen && isLeadingDropDownOpen)
    ) {
      setIsLeadingDropDownOpen(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isTrailingDropDownOpen, isDatePickerBodyOpen]);

  useEffect(() => {
    if (isLeadingDropDownOpen && isTrailingDropDownOpen) {
      setIsTrailingDropDownOpen(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLeadingDropDownOpen]);

  const leadingDropDown =
    leading && getComponentId(leading as React.ReactElement) === 'Dropdown' ? leading : null;

  const trailingDropdown =
    trailing && getComponentId(trailing as React.ReactElement) === 'Dropdown' ? trailing : null;
  // we need to look into name of component and check if it 's and icon or a dropdown
  const _leadingIcon: IconComponent | undefined = isIconComponent(leading)
    ? (leading as IconComponent)
    : undefined;

  const _trailingIcon: IconComponent | undefined = isIconComponent(trailing)
    ? (trailing as IconComponent)
    : undefined;
  const hasLeadingInteractionElement = !_leadingIcon && !leadingDropDown && leading;

  const hasTrailingInteractionElement = !_trailingIcon && !trailingDropdown && trailing;

  const renderDropdown = (
    dropdown: React.ReactElement,
    isOpen: boolean,
    setIsOpen: (isOpen: boolean) => void,
    defaultPlacement: 'bottom-start' | 'bottom-end',
  ): React.ReactElement | null => {
    if (!dropdown) {
      return null;
    }
    return React.cloneElement(dropdown, {
      selectionType: 'single',
      isOpen,
      onOpenChange: (isOpen: boolean) => {
        setIsOpen(isOpen);
      },
      children: React.Children.map(dropdown.props.children, (child) => {
        if (child.type === DropdownOverlay) {
          return React.cloneElement(child, {
            referenceRef: textInputWrapperRef,
            _isNestedDropdown: true,
            defaultPlacement,
          });
        }
        return child;
      }),
    });
  };

  const renderLeadingDropDown = renderDropdown(
    leadingDropDown as React.ReactElement,
    isLeadingDropDownOpen,
    setIsLeadingDropDownOpen,
    'bottom-start',
  );
  const renderTrailingDropDown = renderDropdown(
    trailingDropdown as React.ReactElement,
    isTrailingDropDownOpen,
    setIsTrailingDropDownOpen,
    'bottom-end',
  );

  React.useEffect(() => {
    setShouldShowClearButton(Boolean(showClearButton && (defaultValue ?? inputValue)));
  }, [showClearButton, defaultValue, inputValue]);

  const renderClearButton = (): React.ReactElement => {
    return (
      <IconButton
        size="medium"
        icon={CloseIcon}
        onClick={() => {
          if (isEmpty(inputValue) && textInputRef.current) {
            // when the input field is uncontrolled take the ref and clear the input and then call the onClearButtonClick function
            if (isReactNative(textInputRef.current)) {
              textInputRef.current.clear();
              textInputRef.current.focus();
            } else if (textInputRef.current instanceof HTMLInputElement) {
              textInputRef.current.value = '';
              textInputRef.current.focus();
            }
          }
          handleTagsClear();
          // if the input field is controlled just call the click handler and the value change shall be left upto the consumer
          onClearButtonClick?.();
          textInputRef?.current?.focus();
          setShouldShowClearButton(false);
        }}
        isDisabled={isDisabled}
        accessibilityLabel="Clear Input Content"
      />
    );
  };
  const hasTrailingDropDown = Boolean(trailingDropdown);

  const renderInteractionElement = (): ReactNode => {
    if (isLoading) {
      return <Spinner accessibilityLabel="Loading Content" color="primary" />;
    }

    if (shouldShowClearButton && hasTrailingDropDown) {
      return (
        <BaseBox display="flex" gap="spacing.3">
          {renderClearButton()} <Divider orientation="vertical" />
        </BaseBox>
      );
    }

    if (showClearButton && hasTrailingInteractionElement) {
      return (
        <BaseBox display="flex" gap="spacing.3">
          {renderClearButton()} <Divider orientation="vertical" /> {trailing as React.ReactElement}
        </BaseBox>
      );
    }

    if (shouldShowClearButton) {
      return renderClearButton();
    }

    if (hasTrailingInteractionElement) {
      return trailing as React.ReactElement;
    }
    return null;
  };
  return (
    <BaseInput
      id="textinput"
      componentName={MetaConstants.TextInput}
      ref={mergedRef}
      setInputWrapperRef={(wrapperNode) => {
        textInputWrapperRef.current = wrapperNode;
      }}
      label={label as string}
      labelSuffix={labelSuffix}
      labelTrailing={labelTrailing}
      accessibilityLabel={accessibilityLabel}
      hideLabelText={!Boolean(label)}
      labelPosition={labelPosition}
      placeholder={placeholder}
      // CONTROLLED/UNCONTROLLED INPUT LOGIC:
      // For inputs WITHOUT format:
      //   - Use standard React controlled/uncontrolled logic
      //   - Controlled: user provides `value` prop → use `value` prop
      //   - Uncontrolled: user provides `defaultValue` prop → use `defaultValue` prop
      //
      // For inputs WITH format:
      //   - Formatting requires controlled mode to re-render and show formatted values
      //   - Case 1: Only `value` provided → defaultValue: undefined, value: formattedValue (normal controlled)
      //   - Case 2: Only `defaultValue` provided → defaultValue: undefined, value: formattedValue (convert to controlled)
      //   - Case 3: Both `value` and `defaultValue` provided → defaultValue: defaultValue, value: formattedValue (let BaseInput detect conflict and throw error)
      //
      defaultValue={
        format
          ? value !== undefined && defaultValue !== undefined
            ? defaultValue
            : undefined
          : defaultValue
      }
      value={format ? inputValue : value}
      name={name}
      maxCharacters={effectiveMaxCharacters}
      isDropdownTrigger={isTaggedInput}
      tags={isTaggedInput ? getTags({ size }) : undefined}
      showAllTags={isInputFocussed}
      maxTagRows="single"
      activeTagIndex={activeTagIndex}
      setActiveTagIndex={setActiveTagIndex}
      leadingDropDown={renderLeadingDropDown}
      trailingDropDown={renderTrailingDropDown}
      leadingInteractionElement={
        hasLeadingInteractionElement ? (leading as React.ReactElement) : null
      }
      onChange={({ name, value }: { name?: string; value?: string }) => {
        if (showClearButton && value?.length) {
          // show the clear button when the user starts typing in
          setShouldShowClearButton(true);
        }

        if (shouldShowClearButton && !value?.length) {
          // hide the clear button when the input field is empty
          setShouldShowClearButton(false);
        }

        handleTaggedInputChange({ name, value });
        handleOnChange({ name, value });
      }}
      onClick={onClick}
      onFocus={(e) => {
        setIsInputFocussed(true);
        onFocus?.(e);
      }}
      onBlur={(e) => {
        setIsInputFocussed(false);
        onBlur?.(e);
      }}
      onKeyDown={(e) => {
        handleTaggedInputKeydown(e);
        onKeyDown?.(e);
        if (format) {
          formattingResult.handleKeyDown(e.event);
        }
      }}
      onSubmit={onSubmit}
      isDisabled={isDisabled}
      necessityIndicator={necessityIndicator}
      isRequired={isRequired}
      leadingIcon={_leadingIcon ?? leadingIcon ?? icon}
      prefix={prefix}
      trailingInteractionElement={renderInteractionElement()}
      trailingIcon={_trailingIcon ?? trailingIcon}
      suffix={suffix}
      validationState={validationState}
      errorText={errorText}
      helpText={helpText}
      successText={successText}
      trailingFooterSlot={(value) => {
        return format ? null : effectiveMaxCharacters ? (
          <BaseBox marginTop={hintMarginTop[size]} marginRight="spacing.1">
            <CharacterCounter
              currentCount={value?.length ?? 0}
              maxCount={effectiveMaxCharacters}
              size={size}
            />
          </BaseBox>
        ) : null;
      }}
      // eslint-disable-next-line jsx-a11y/no-autofocus
      autoFocus={autoFocus}
      testID={testID}
      {...getKeyboardAndAutocompleteProps({
        type,
        keyboardReturnKeyType,
        autoCompleteSuggestionType,
        autoCapitalize,
      })}
      size={size}
      {...rest}
    />
  );
};

const TextInput = assignWithoutSideEffects(React.forwardRef(_TextInput), {
  displayName: 'TextInput',
});

export type { TextInputProps };
export { TextInput };
