// packages/blade/src/components/Skeleton/Skeleton.tsx
/* eslint-disable @typescript-eslint/no-unnecessary-type-assertion */
import { PulseAnimation } from './PulseAnimation';
import type { SkeletonProps } from './types';
import { getStyledProps } from '~components/Box/styledProps';
import { makeAccessible } from '~utils/makeAccessible';
import { metaAttribute, MetaConstants } from '~utils/metaAttribute';

const Skeleton = ({
  width,
  maxWidth,
  minWidth,
  height,
  maxHeight,
  minHeight,
  borderRadius,
  flexWrap,
  flexDirection,
  flexGrow,
  flexShrink,
  flexBasis,
  alignItems,
  alignContent,
  alignSelf,
  justifyItems,
  justifyContent,
  justifySelf,
  placeSelf,
  placeItems,
  order,
  testID,
  ...props
}: SkeletonProps): React.ReactElement => {
  return (
    <PulseAnimation
      width={width}
      minWidth={minWidth}
      maxWidth={maxWidth}
      height={height}
      minHeight={minHeight}
      maxHeight={maxHeight}
      borderRadius={borderRadius}
      flexWrap={flexWrap}
      flexDirection={flexDirection}
      flexGrow={flexGrow}
      flexShrink={flexShrink}
      flexBasis={flexBasis}
      alignItems={alignItems}
      alignContent={alignContent}
      alignSelf={alignSelf}
      justifyItems={justifyItems}
      justifyContent={justifyContent}
      justifySelf={justifySelf}
      placeSelf={placeSelf}
      placeItems={placeItems}
      order={order}
      {...getStyledProps(props)}
      {...makeAccessible({ hidden: true })}
      {...metaAttribute({ name: MetaConstants.Skeleton, testID })}
    />
  );
};

export { Skeleton };

// packages/blade-svelte/src/components/Skeleton/Skeleton.svelte
<script lang="ts">
  import {
    metaAttribute,
    MetaConstants,
    makeAccessible,
    makeAnalyticsAttribute,
    getStyledPropsClasses,
    kebabCase,
    combineStyleStrings,
  } from '@razorpay/blade-core/utils';
  import { getSkeletonClasses, getSkeletonInlineStyle } from '@razorpay/blade-core/styles';
  import type { SkeletonProps } from './types';

  let {
    width,
    maxWidth,
    minWidth,
    height,
    maxHeight,
    minHeight,
    borderRadius,
    flexDirection,
    flexWrap,
    flexGrow,
    flexShrink,
    flexBasis,
    alignItems,
    alignContent,
    alignSelf,
    justifyItems,
    justifyContent,
    justifySelf,
    placeSelf,
    placeItems,
    order,
    testID,
    ...rest
  }: SkeletonProps = $props();

  const skeletonClassNames = $derived(
    getSkeletonClasses({
      borderRadius,
      flexDirection,
      flexWrap,
      alignItems,
      justifyContent,
      alignSelf,
      justifySelf,
      placeSelf,
    }),
  );

  const styledProps = $derived(getStyledPropsClasses(rest));

  const combinedClasses = $derived(
    [skeletonClassNames, ...(styledProps.classes || [])].filter(Boolean).join(' '),
  );

  const ownInlineStyle = $derived(
    getSkeletonInlineStyle({
      width,
      maxWidth,
      minWidth,
      height,
      maxHeight,
      minHeight,
      alignContent,
      justifyItems,
      placeItems,
      flexGrow,
      flexShrink,
      flexBasis,
      order,
    }),
  );

  const styledPropsInlineStyle = $derived.by(() => {
    const entries = Object.entries(styledProps.inlineStyles ?? {});
    if (entries.length === 0) return undefined;
    return entries.map(([key, value]) => `${kebabCase(key)}: ${value}`).join('; ');
  });

  const finalStyle = $derived(combineStyleStrings(ownInlineStyle, styledPropsInlineStyle) || undefined);

  const a11yAttrs = makeAccessible({ hidden: true });
  const metaAttrs = metaAttribute({ name: MetaConstants.Skeleton, testID });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));
</script>

<div
  class={combinedClasses}
  style={finalStyle}
  {...a11yAttrs}
  {...metaAttrs}
  {...analyticsAttrs}
></div>
