// packages/blade-svelte/src/components/CardGroup/CardGroupCollapsibleItemBody.svelte
<script lang="ts">
  import { metaAttribute, MetaConstants } from '@razorpay/blade-core/utils';
  import { getCardGroupTemplateClasses } from '@razorpay/blade-core/styles';
  import CollapsibleBody from '../Collapsible/CollapsibleBody.svelte';
  import { setInsideCardGroupBody } from './cardGroupContext';
  import type { CardGroupCollapsibleItemBodyProps } from './types';

  const templateClasses = getCardGroupTemplateClasses();

  let { children: content, testID, ...rest }: CardGroupCollapsibleItemBodyProps = $props();

  // Content rendered here is not a disclosure trigger — see cardGroupContext.
  setInsideCardGroupBody();

  const metaAttrs = $derived(
    metaAttribute({ name: MetaConstants.CardGroupCollapsibleItemBody, testID }),
  );
</script>

<CollapsibleBody _hasMargin={false} {...rest}>
  <div class={templateClasses.cardGroupCollapsibleBody} {...metaAttrs}>
    {#if typeof content === 'string'}
      {content}
    {:else}
      {@render content()}
    {/if}
  </div>
</CollapsibleBody>

// packages/blade/src/components/CardGroup/CardGroupCollapsibleItemBody.tsx
import React from 'react';
import { CollapsibleBody } from '~components/Collapsible';
import { Divider } from '~components/Divider';
import { CardGroupBodyProvider } from './CardGroupContext';
import { ComponentIds } from './componentIds';
import type { CardGroupCollapsibleItemBodyProps } from './types';
import BaseBox from '~components/Box/BaseBox';
import { metaAttribute, MetaConstants } from '~utils/metaAttribute';
import { makeAnalyticsAttribute } from '~utils/makeAnalyticsAttribute';
import { assignWithoutSideEffects } from '~utils/assignWithoutSideEffects';

const _CardGroupCollapsibleItemBody = ({
  children,
  testID,
  ...rest
}: CardGroupCollapsibleItemBodyProps): React.ReactElement => {
  return (
    <CollapsibleBody _hasMargin={false} width="100%" {...makeAnalyticsAttribute(rest)}>
      {/* Content here is not a disclosure trigger — see CardGroupContext. */}
      <CardGroupBodyProvider>
        {/* Full-bleed divider separating the revealed content from the trigger row. */}
        <Divider />
        <BaseBox
          paddingY="spacing.4"
          paddingX="spacing.5"
          {...metaAttribute({ name: MetaConstants.CardGroupCollapsibleItemBody, testID })}
        >
          {children}
        </BaseBox>
      </CardGroupBodyProvider>
    </CollapsibleBody>
  );
};

const CardGroupCollapsibleItemBody = assignWithoutSideEffects(_CardGroupCollapsibleItemBody, {
  displayName: 'CardGroupCollapsibleItemBody',
  componentId: ComponentIds.CardGroupCollapsibleItemBody,
});

export { CardGroupCollapsibleItemBody };
