// packages/blade/src/components/Input/PasswordInput/PasswordInput.tsx
import type { ReactElement, ReactNode } from 'react';
import { useState } from 'react';
import type { BaseInputProps } from '../BaseInput';
import { BaseInput } from '../BaseInput';
import { EyeIcon, EyeOffIcon } from '~components/Icons';
import Box from '~components/Box';
import { CharacterCounter } from '~components/Form/CharacterCounter';
import { IconButton } from '~components/Button/IconButton';

type PasswordInputExtraProps = {
  /**
   * Shows a reveal button to toggle password visibility
   *
   * @default true
   */
  showRevealButton?: boolean;

  /**
   * Displays asterisk (`*`) when `isRequired` is enabled
   *
   * @default none
   */
  necessityIndicator?: Exclude<BaseInputProps['necessityIndicator'], 'optional'>;

  /**
   * Determines what autoComplete suggestion type to show. Defaults to using platform heuristics.
   *
   * It's not recommended to turn this off in favor of safe password practices.
   * Providing `password` or `newPassword` is more informative to the platform for browser autofill or password managers.
   *
   * **Note**: Using `newPassword` on iOS has some [known issue](https://github.com/facebook/react-native/issues/21911) on React Native
   *
   * Internally it'll render platform specific attributes:
   *
   * - web: `autocomplete`
   * - iOS: `textContentType`
   * - android: `autoComplete`
   *
   */
  autoCompleteSuggestionType?: Extract<
    BaseInputProps['autoCompleteSuggestionType'],
    'none' | 'password' | 'newPassword'
  >;
};

type PasswordInputProps = Pick<
  BaseInputProps,
  | 'label'
  | 'labelPosition'
  | 'maxCharacters'
  | 'validationState'
  | 'errorText'
  | 'successText'
  | 'helpText'
  | 'isDisabled'
  | 'defaultValue'
  | 'placeholder'
  | 'isRequired'
  | 'value'
  | 'onChange'
  | 'onBlur'
  | 'onFocus'
  | 'name'
  | 'autoFocus'
  | 'keyboardReturnKeyType'
  | 'autoCompleteSuggestionType'
> &
  PasswordInputExtraProps;

const PasswordInput = ({
  label,
  labelPosition = 'top',
  showRevealButton = true,
  maxCharacters,
  validationState,
  errorText,
  successText,
  helpText,
  isDisabled = false,
  defaultValue,
  placeholder,
  isRequired = false,
  necessityIndicator = 'none',
  value,
  onChange,
  onFocus,
  onBlur,
  name,
  autoFocus = false,
  keyboardReturnKeyType = 'done',
  autoCompleteSuggestionType,
}: PasswordInputProps): ReactElement => {
  const [isRevealed, setIsRevealed] = useState(false);
  const isEnabled = !isDisabled;

  // If input is disabled reveal button shouldn't be present and input should be masked
  const isRevealedAndEnabled = isRevealed && isEnabled;

  const toggleIsRevealed = (): void => setIsRevealed((revealed) => !revealed);
  const accessibilityLabel = isRevealedAndEnabled ? 'Hide password' : 'Show password';
  const type = isRevealedAndEnabled ? 'text' : 'password';

  const revealButtonIcon = isRevealedAndEnabled ? EyeOffIcon : EyeIcon;
  const revealButton =
    showRevealButton && !isDisabled ? (
      <IconButton
        size="medium"
        icon={revealButtonIcon}
        onClick={toggleIsRevealed}
        accessibilityLabel={accessibilityLabel}
      />
    ) : null;

  const trailingFooterSlot = (value?: string): ReactNode =>
    maxCharacters ? (
      <Box marginTop="spacing.2" marginRight="spacing.1">
        <CharacterCounter currentCount={value?.length ?? 0} maxCount={maxCharacters} />
      </Box>
    ) : null;

  return (
    <BaseInput
      componentName="password-input"
      id="password-field"
      label={label}
      labelPosition={labelPosition}
      type={type}
      interactionElement={revealButton}
      trailingFooterSlot={trailingFooterSlot}
      maxCharacters={maxCharacters}
      validationState={validationState}
      errorText={errorText}
      successText={successText}
      helpText={helpText}
      isDisabled={isDisabled}
      defaultValue={defaultValue}
      placeholder={placeholder}
      isRequired={isRequired}
      necessityIndicator={necessityIndicator}
      value={value}
      onChange={onChange}
      onBlur={onBlur}
      onFocus={onFocus}
      name={name}
      // eslint-disable-next-line jsx-a11y/no-autofocus
      autoFocus={autoFocus}
      autoCompleteSuggestionType={autoCompleteSuggestionType}
      keyboardReturnKeyType={keyboardReturnKeyType}
    />
  );
};

export { PasswordInputProps, PasswordInput };

// packages/blade-svelte/src-cx/components/password-input/PasswordInput.svelte
<script lang="ts">
  import type { ComponentProps } from 'svelte';
  import { createPasswordReveal } from '../../runes/text-input/reveal.svelte';
  import IconButton from '../icon-button/IconButton.svelte';
  import { eye, eyeOff } from '../icons';
  import TextInput from '../text-input/TextInput.svelte';

  type TextInputProps = ComponentProps<typeof TextInput>;

  // Blade's PasswordInput: TextInput's field chrome, masked, with a button
  // that reveals the text. No affixes, format or keyboard of its own.
  type Props = Pick<
    TextInputProps,
    | 'label'
    | 'accessibilityLabel'
    | 'labelArea'
    | 'value'
    | 'placeholder'
    | 'onChange'
    | 'onBlur'
    | 'onFocus'
    | 'isDisabled'
    | 'isRequired'
    | 'validationState'
    | 'helpText'
    | 'errorText'
    | 'successText'
    | 'maxCharacters'
    | 'autoFocus'
    | 'enterKeyHint'
    | 'name'
    | 'span'
    | 'size'
    | 'testID'
    | 'class'
    | 'attach'
  > & {
    /** `*` after the label; a password is never marked optional. @default 'none' */
    necessityIndicator?: 'required' | 'none';
    /**
     * What the browser or a password manager offers: `current-password` to
     * sign in, `new-password` to set one. Unset, the browser guesses.
     */
    autoComplete?: 'off' | 'current-password' | 'new-password';
    /** A button that shows and hides the password. @default true */
    showRevealButton?: boolean;
  };

  let {
    value = $bindable(''),
    isDisabled = false,
    showRevealButton = true,
    ...rest
  }: Props = $props();

  const reveal = createPasswordReveal({ isDisabled: () => isDisabled });
</script>

{#snippet revealButton()}
  <IconButton
    icon={reveal.isRevealed ? eyeOff : eye}
    size="medium"
    accessibilityLabel={reveal.isRevealed ? 'Hide password' : 'Show password'}
    onClick={reveal.toggle}
  />
{/snippet}

<TextInput
  bind:value
  {...rest}
  {isDisabled}
  type={reveal.isRevealed ? 'text' : 'password'}
  autoCapitalize="none"
  trailing={showRevealButton && !isDisabled ? revealButton : undefined}
/>
