// packages/blade/src/components/BottomSheet/BottomSheet.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable react/jsx-no-useless-fragment */
/* eslint-disable consistent-return */
/* eslint-disable @typescript-eslint/explicit-function-return-type */
import React from 'react';
import styled from 'styled-components';
import { rubberbandIfOutOfBounds, useDrag } from '@use-gesture/react';
import usePresence from 'use-presence';
import { clearAllBodyScrollLocks } from 'body-scroll-lock';
import { BottomSheetGrabHandle, BottomSheetHeader } from './BottomSheetHeader';
import { BottomSheetBody } from './BottomSheetBody';
import type { SnapPoints } from './utils';
import { computeMaxContent, computeSnapPointBounds } from './utils';
import { BottomSheetBackdrop } from './BottomSheetBackdrop';
import { BottomSheetContext, useBottomSheetAndDropdownGlue } from './BottomSheetContext';
import { ComponentIds } from './componentIds';
import { BottomSheetCloseButton } from './BottomSheetCloseButton';
import { useBottomSheetStack } from './BottomSheetStack';
import BaseBox from '~components/Box/BaseBox';
import { makeMotionTime, makeSpace } from '~utils';

import { useScrollLock } from '~src/hooks/useScrollLock';
import { useWindowSize } from '~src/hooks/useWindowSize';
import { useIsomorphicLayoutEffect } from '~src/hooks/useIsomorphicLayoutEffect';
import { assignWithoutSideEffects } from '~src/utils/assignWithoutSideEffects';
import { useTheme } from '~components/BladeProvider';
import { useId } from '~src/hooks/useId';

type BottomSheetProps = {
  isOpen?: boolean;
  onDismiss?: () => void;
  children: React.ReactNode;
  initialFocusRef?: React.MutableRefObject<any>;
  snapPoints?: SnapPoints;
};

export const BOTTOM_SHEET_EASING = 'cubic-bezier(.15,0,.24,.97)';

const BottomSheetSurface = styled.div<{
  windowHeight: number;
  isDragging: boolean;
}>(({ theme, windowHeight, isDragging }) => {
  const offsetX = theme.shadows.offsetX.level[1];
  const offsetY = theme.shadows.offsetY.level[1];
  const blur = theme.shadows.blurRadius.level[1];
  const shadowColor = theme.shadows.color.level[1];

  const shadowLayer1 = `${offsetX}px ${offsetY}px ${blur}px 0px ${shadowColor}`;
  const shadowLayer2 = `0px 0px 1px 0px ${shadowColor}`;

  return {
    background: theme.colors.surface.background.level2.lowContrast,
    // TODO: we do not have 16px radius token
    borderTopLeftRadius: makeSpace(theme.spacing[5]),
    borderTopRightRadius: makeSpace(theme.spacing[5]),
    borderColor: theme.colors.surface.border.normal.lowContrast,
    boxShadow: `${shadowLayer1}, ${shadowLayer2}`,
    opacity: 0,
    pointerEvents: 'none',
    transitionDuration: isDragging
      ? undefined
      : `${makeMotionTime(theme.motion.duration.moderate)}`,
    transitionTimingFunction: BOTTOM_SHEET_EASING,
    willChange: 'transform, opacity, height',
    transitionProperty: 'transform, opacity, height',
    position: 'fixed',
    left: 0,
    right: 0,
    bottom: 0,
    top: windowHeight,
    backgroundColor: theme.colors.surface.background.level2.lowContrast,
    justifyContent: 'center',
    alignItems: 'center',
    touchAction: 'none',
    overflow: 'hidden',
  };
});

const _BottomSheet = ({
  isOpen,
  onDismiss,
  children,
  initialFocusRef,
  snapPoints = [0.35, 0.5, 0.85],
}: BottomSheetProps): React.ReactElement => {
  const { theme } = useTheme();
  const dimensions = useWindowSize();
  const [contentHeight, setContentHeight] = React.useState(0);
  const [headerHeight, setHeaderHeight] = React.useState(0);
  const [footerHeight, setFooterHeight] = React.useState(0);
  const [grabHandleHeight, setGrabHandleHeight] = React.useState(0);

  const bottomSheetAndDropdownGlue = useBottomSheetAndDropdownGlue();
  const [positionY, _setPositionY] = React.useState(0);
  const _isOpen = bottomSheetAndDropdownGlue?.isOpen ?? isOpen;
  const [isDragging, setIsDragging] = React.useState(false);

  const preventScrollingRef = React.useRef(true);
  const scrollRef = React.useRef<HTMLDivElement>(null);
  const grabHandleRef = React.useRef<HTMLDivElement>(null);
  const originalFocusElement = React.useRef<HTMLElement>(null);
  const defaultInitialFocusRef = React.useRef<any>(null);

  const id = useId();
  const {
    stack,
    addBottomSheetToStack,
    removeBottomSheetFromStack,
    getTopOfTheStack,
    getCurrentStackIndexById,
  } = useBottomSheetStack();
  const currentStackIndex = getCurrentStackIndexById(id);
  const isOnTopOfStack = getTopOfTheStack() === id;
  const zIndex = 100 - currentStackIndex;

  const setPositionY = React.useCallback(
    (value: number, limit = true) => {
      const maxValue = computeMaxContent({
        contentHeight,
        footerHeight,
        headerHeight: headerHeight + grabHandleHeight,
        maxHeight: value,
      });
      _setPositionY(limit ? maxValue : value);
    },
    [contentHeight, footerHeight, grabHandleHeight, headerHeight],
  );

  // locks the body scroll to prevent accidental scrolling of content when we drag the sheet
  // We are ready when we calculated the height of the content
  const isReady = contentHeight > 0;
  // only lock the body when we atleast have 1 bottomsheet open
  const shouldLock = isReady && stack.length > 0;
  const scrollLockRef = useScrollLock({
    enabled: shouldLock,
    targetRef: scrollRef,
    reserveScrollBarGap: true,
  });

  // clear all body locks to avoid memory leaks & accidental body locking
  React.useEffect(() => {
    const hasNoBottomSheets = stack.length < 1;
    if (hasNoBottomSheets) {
      clearAllBodyScrollLocks();
    }
  }, [stack]);

  // take the grabHandle's height into headerHeight too
  useIsomorphicLayoutEffect(() => {
    if (!grabHandleRef.current) return;
    setGrabHandleHeight(grabHandleRef.current.getBoundingClientRect().height);
  }, [grabHandleRef.current, _isOpen]);

  const returnFocus = React.useCallback(() => {
    if (!originalFocusElement.current) return;
    originalFocusElement.current.focus();
    // After returning focus we will clear the original focus
    // Because if sheet can be opened up via multiple triggers
    // We want to ensure the focus returns back to the most recent triggerer
    // @ts-expect-error this is a mutable ref
    originalFocusElement.current = null;
  }, [originalFocusElement]);

  const focusOnInitialRef = React.useCallback(() => {
    if (!initialFocusRef) {
      // focus on close button
      defaultInitialFocusRef.current?.focus();
    } else {
      // focus on the initialRef passed by the user
      initialFocusRef.current?.focus();
    }
  }, [initialFocusRef]);

  const close = React.useCallback(() => {
    setPositionY(0);
    returnFocus();
    onDismiss?.();
    // close the select dropdown as well
    bottomSheetAndDropdownGlue?.setIsOpen(false);
  }, [setPositionY, returnFocus, onDismiss, bottomSheetAndDropdownGlue]);

  const open = React.useCallback(() => {
    scrollLockRef.current.activate();
    // @ts-expect-error this is a mutable ref
    originalFocusElement.current = originalFocusElement.current ?? document.activeElement;
    focusOnInitialRef();
  }, [focusOnInitialRef, scrollLockRef]);

  // sync controlled state to our actions
  React.useEffect(() => {
    if (isOpen === true) {
      open();
    }
    if (isOpen === false) {
      close();
    }
  }, [isOpen, close, open]);

  React.useEffect(() => {
    if (isOpen === true) {
      setPositionY(dimensions.height * 0.5);
    }
  }, [isOpen, setPositionY, dimensions.height]);

  // sync the select dropdown's state with bottomsheet's state
  React.useEffect(() => {
    if (!bottomSheetAndDropdownGlue) return;

    // this will let the Dropdown component know that it's rendering a bottomsheet
    bottomSheetAndDropdownGlue.setDropdownHasBottomSheet(true);

    if (bottomSheetAndDropdownGlue.isOpen) {
      open();
    }

    if (
      !bottomSheetAndDropdownGlue.isOpen &&
      bottomSheetAndDropdownGlue.selectionType === 'single'
    ) {
      close();
    }
  }, [close, open, bottomSheetAndDropdownGlue]);

  /*
      1. The content should not be scrollable on lower or middle snapPoints
      2. If we reach the top snapPoint we make the content scrollable
      3. scrolling down the content will work as usual
      4. but if the scroll position is at top and then we drag down on the content body
         the bottom-sheet will start the dragging and we will set the scroll to 'none'
    */
  const bind = useDrag(
    ({
      active,
      last,
      cancel,
      tap,
      movement: [_movementX, movementY],
      velocity: [_velocityX, velocityY],
      lastOffset: [_, lastOffsetY],
      down,
      dragging,
      args: [{ isContentDragging = false } = {}] = [],
    }) => {
      setIsDragging(Boolean(dragging));
      // lastOffsetY is the previous position user stopped dragging the sheet
      // movementY is the drag amount from the bottom of the screen, so as you drag up the movementY goes into negatives
      // and rawY is the calculated offset from the last position of the bottomsheet to current drag amount.
      const rawY = lastOffsetY - movementY;

      const lowerSnapPoint = dimensions.height * snapPoints[0];
      const upperSnapPoint = dimensions.height * snapPoints[snapPoints.length - 1];

      // predictedY is used to create velocity driven swipe
      // the faster you swipe the more distance you cover
      // this enables users to reach upper & lower snappoint with a single swipe
      const predictedDistance = movementY * (velocityY / 2);
      const predictedY = Math.max(
        lowerSnapPoint,
        Math.min(upperSnapPoint, rawY - predictedDistance * 2),
      );

      let newY = rawY;

      if (down) {
        // Ensure that users aren't able to drag the sheet
        // more than the upperSnapPoint or maximum height of the sheet
        // this is basically a clamp() function but creates a nice rubberband effect
        const dampening = 0.55;
        const totalHeight = grabHandleHeight + headerHeight + footerHeight + contentHeight;
        if (totalHeight < upperSnapPoint) {
          newY = rubberbandIfOutOfBounds(rawY, 0, totalHeight, dampening);
        } else {
          newY = rubberbandIfOutOfBounds(rawY, 0, upperSnapPoint, dampening);
        }
      } else {
        newY = predictedY;
      }

      const isPosAtUpperSnapPoint = newY >= upperSnapPoint;

      if (isContentDragging) {
        if (isPosAtUpperSnapPoint) {
          newY = upperSnapPoint;
        }

        // keep the newY at upper snap point
        // until the scrollable content is not at top
        // and previously saved Y position is greater than or equal to upper snap point
        // Note: how using newY won't work here since we need the previous value of the newY
        // since we always keep updating the newY,
        // this is cruicial in making the scroll feel natural
        const isContentScrolledAtTop = scrollRef.current && scrollRef.current.scrollTop <= 0;
        if (lastOffsetY === upperSnapPoint && !isContentScrolledAtTop) {
          newY = upperSnapPoint;
        }
        preventScrollingRef.current = newY < upperSnapPoint;
      }

      const shouldClose = newY < lowerSnapPoint;
      if (shouldClose) {
        setIsDragging(false);
        close();
        cancel();
        return;
      }

      if (last) {
        // calculate the nearest snapPoint
        const [nearest] = computeSnapPointBounds(
          newY,
          snapPoints.map((point) => dimensions.height * point) as SnapPoints,
        );

        // if we stop dragging assign snap to the nearest point
        if (!active && !tap) {
          newY = nearest;
        }
      }

      setPositionY(newY, !down);
    },
    {
      from: [0, positionY],
      filterTaps: true,
      enabled: isOnTopOfStack && _isOpen,
    },
  );

  // Here we are preventing the scrolling of the content, until the preventScrollingRef value is true
  useIsomorphicLayoutEffect(() => {
    const scrollElement = scrollRef.current;
    if (!scrollElement) return;

    const preventScrolling = (e: Event) => {
      if (preventScrollingRef?.current) {
        e.preventDefault();
      }
    };

    // https://www.bram.us/2016/05/02/prevent-overscroll-bounce-in-ios-mobilesafari-pure-css/
    const preventSafariOverscroll = (e: Event) => {
      if (scrollElement.scrollTop < 0) {
        // TODO: figure this out, it doesn't seem to work >iOS12
        // requestAnimationFrame(() => {
        //   elem.style.overflow = 'hidden';
        //   elem.scrollTop = 0;
        //   elem.style.removeProperty('overflow');
        // });
        e.preventDefault();
      }
    };

    scrollElement.addEventListener('scroll', preventScrolling);
    scrollElement.addEventListener('touchmove', preventScrolling);
    scrollElement.addEventListener('touchstart', preventSafariOverscroll);
    return () => {
      scrollElement.removeEventListener('scroll', preventScrolling);
      scrollElement.removeEventListener('touchmove', preventScrolling);
      scrollElement.removeEventListener('touchstart', preventSafariOverscroll);
    };
  }, [scrollRef.current]);

  // usePresence hook waits for the animation to finish before unmounting the component
  // It's similar to framer-motions usePresence hook
  // https://www.framer.com/docs/animate-presence/#usepresence
  const { isMounted, isVisible } = usePresence(Boolean(_isOpen), {
    transitionDuration: theme.motion.duration.moderate,
  });

  const contextValue = React.useMemo(
    () => ({
      isInBottomSheet: true,
      isOpen: Boolean(isVisible),
      close,
      posY: positionY,
      headerHeight,
      contentHeight,
      footerHeight,
      setContentHeight,
      setFooterHeight,
      setHeaderHeight,
      scrollRef,
      bind,
      defaultInitialFocusRef,
    }),
    [
      isVisible,
      close,
      positionY,
      headerHeight,
      contentHeight,
      footerHeight,
      setContentHeight,
      setFooterHeight,
      setHeaderHeight,
      scrollRef,
      bind,
      defaultInitialFocusRef,
    ],
  );

  React.useEffect(() => {
    if (isMounted) {
      addBottomSheetToStack(id);
    } else {
      removeBottomSheetFromStack(id);
    }
  }, [addBottomSheetToStack, id, isMounted, removeBottomSheetFromStack]);

  // We will need to reset these values otherwise the next time the bottomsheet opens
  // this will be populated and the animations won't run
  // why?: because how the usePresence hook works, we actually just unmount the
  // html contents not the whole <BottomSheet /> react component
  React.useEffect(() => {
    if (!isMounted) {
      setHeaderHeight(0);
      setFooterHeight(0);
      setContentHeight(0);
    }
  }, [isMounted, scrollLockRef]);

  // We don't want to destroy the react tree when we are rendering inside Dropdown
  // Because if we bail out early then ActionList won't render,
  // and Dropdown manages it's state based on the rendered JSX of ActionList
  // If we don't render ActionList Dropdown state will reset each time we open/close BottomSheet
  const isInsideDropdown = Boolean(bottomSheetAndDropdownGlue);
  if (!isMounted && !isInsideDropdown) {
    return <></>;
  }

  return (
    <BottomSheetContext.Provider value={contextValue}>
      {/* This has to be isVisible */}
      {/* TODO: fix opactiy flicker */}
      <BottomSheetBackdrop zIndex={zIndex} />
      <BottomSheetSurface
        data-surface
        windowHeight={dimensions.height}
        isDragging={isDragging}
        style={{
          opacity: isVisible ? 1 : 0,
          pointerEvents: isVisible ? 'all' : 'none',
          height: positionY,
          bottom: 0,
          top: 'auto',
          zIndex,
        }}
      >
        <BaseBox height="100%" display="flex" flexDirection="column">
          <BottomSheetCloseButton />
          <BottomSheetGrabHandle ref={grabHandleRef} {...bind()} />
          {children}
        </BaseBox>
      </BottomSheetSurface>
    </BottomSheetContext.Provider>
  );
};

const BottomSheet = assignWithoutSideEffects(_BottomSheet, {
  componentId: ComponentIds.BottomSheet,
});

export { BottomSheet, BottomSheetBody, BottomSheetHeader, BottomSheetProps };

// packages/blade-svelte/src/components/BottomSheet/BottomSheet.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { DragGesture, rubberbandIfOutOfBounds } from '@use-gesture/vanilla';
  import {
    disableBodyScroll,
    enableBodyScroll,
    clearAllBodyScrollLocks,
  } from 'body-scroll-lock-upgrade';
  import {
    metaAttribute,
    MetaConstants,
    makeAccessible,
    makeAnalyticsAttribute,
    getStyledPropsClasses,
  } from '@razorpay/blade-core/utils';
  import {
    BOTTOM_SHEET_Z_INDEX,
    BOTTOM_SHEET_DEFAULT_SNAP_POINTS,
    bottomSheetSurfaceClass,
    bottomSheetInnerWrapperClass,
    bottomSheetGrabHandleClass,
    bottomSheetGrabHandleFloatingClass,
    bottomSheetPortalRootClass,
    getBottomSheetTemplateClasses,
  } from '@razorpay/blade-core/styles';
  import {
    bottomSheetStack,
    addBottomSheetToStack,
    removeBottomSheetFromStack,
  } from './bottomSheetStack';
  import { setBottomSheetContext } from './bottomSheetContext';
  import type { BottomSheetContextValue } from './bottomSheetContext';
  import type { BottomSheetProps, SnapPoints } from './types';
  import { computeMaxContent, computeSnapPointBounds } from './utils';
  import BottomSheetBackdrop from './BottomSheetBackdrop.svelte';
  import { portal } from '../../utils/portal';

  /* Anchor structural classes against the Rollup tree-shaker — CSS modules
   * export ESM objects whose unused individual exports otherwise get
   * dropped from the build.
   * eslint-disable-next-line @typescript-eslint/no-unused-vars */
  void getBottomSheetTemplateClasses();

  let {
    isOpen = false,
    onDismiss,
    children,
    initialFocusRef = null,
    snapPoints = [...BOTTOM_SHEET_DEFAULT_SNAP_POINTS] as SnapPoints,
    isDismissible = true,
    zIndex = BOTTOM_SHEET_Z_INDEX,
    portalTarget,
    testID,
    ...rest
  }: BottomSheetProps = $props();

  /* Stable id for the stack — `crypto.randomUUID()` falls back to a Math.random
   * suffix so jsdom (without crypto) still produces a unique value. */
  const id =
    typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
      ? crypto.randomUUID()
      : `bottomsheet-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

  let grabHandleEl = $state<HTMLDivElement | null>(null);
  let scrollEl = $state<HTMLElement | null>(null);
  let defaultFocusEl = $state<HTMLElement | null>(null);
  let originalFocusEl: HTMLElement | null = null;

  /* Measured heights of children (reported via context). */
  let contentHeight = $state(0);
  let headerHeight = $state(0);
  let footerHeight = $state(0);
  let grabHandleHeight = $state(0);

  /* UI state. */
  let positionY = $state(0);
  let isDragging = $state(false);
  let hasBodyPadding = $state(true);
  let isHeaderEmpty = $state(false);
  let windowHeight = $state(typeof window !== 'undefined' ? window.innerHeight : 800);

  /* Presence — DOM stays mounted past `isOpen=false` until the exit
   * transition completes. Mirrors Tooltip's pattern. */
  let isMounted = $state(false);
  let isVisible = $state(false);
  let unmountTimeoutId: ReturnType<typeof setTimeout> | null = null;
  /* Allow ~320ms (--duration-moderate 280ms + buffer) for the exit
   * transition before unmounting. */
  const UNMOUNT_FALLBACK_MS = 320;

  /* Mirrors React's `preventScrollingRef` — set during drag to gate the
   * body's scroll/touchmove listeners below. */
  let preventScrolling = $state(true);

  /* Track stack for reactive z-index. */
  let stackArr = $state<string[]>([]);
  $effect(() => {
    const unsubscribe = bottomSheetStack.subscribe((value) => {
      stackArr = value;
    });
    return unsubscribe;
  });

  const currentStackIndex = $derived(stackArr.indexOf(id));
  const isOnTopOfStack = $derived(stackArr[0] === id);
  const bottomSheetZIndex = $derived(zIndex - Math.max(0, currentStackIndex));

  const totalHeight = $derived(grabHandleHeight + headerHeight + footerHeight + contentHeight);

  let initialSnapPointFraction = $state(snapPoints[1]);

  /* Adjust the initial snap point so a small total content sits on the
   * lowest snap point, otherwise stays on the middle one. Mirrors React. */
  $effect(() => {
    const middleSnapPoint = snapPoints[1] * windowHeight;
    const lowerSnapPoint = snapPoints[0] * windowHeight;
    if (totalHeight > lowerSnapPoint && totalHeight < middleSnapPoint) {
      initialSnapPointFraction = snapPoints[0];
    } else {
      initialSnapPointFraction = snapPoints[1];
    }
  });

  function setPositionY(value: number, limit = true): void {
    if (!limit) {
      positionY = value;
      return;
    }
    const maxValue = computeMaxContent({
      contentHeight,
      footerHeight,
      headerHeight: headerHeight > 0 ? headerHeight + grabHandleHeight : 0,
      maxHeight: value,
    });
    positionY = maxValue;
  }

  function returnFocus(): void {
    if (!originalFocusEl) return;
    try {
      /* `preventScroll` stops the browser scrolling the focus target into
       * view — otherwise returning focus to a trigger inside a scrollable
       * ancestor jumps the host content. Focus still moves for a11y. */
      originalFocusEl.focus({ preventScroll: true });
    } catch {
      /* ignore — element may have been unmounted. */
    }
    originalFocusEl = null;
  }

  function focusOnInitialRef(): void {
    const target = initialFocusRef ?? defaultFocusEl;
    if (!target) return;
    try {
      /* `preventScroll` suppresses the native scroll-focused-element-into-view.
       * The surface is fixed/absolute pinned to the bottom, so without this the
       * browser scrolls the nearest scrollable ancestor of the portal target
       * (e.g. a Checkout modal) and shoves the host content up. Focus still
       * moves into the dialog, so screen-reader/keyboard behaviour is intact. */
      target.focus({ preventScroll: true });
    } catch {
      /* ignore */
    }
  }

  function close(): void {
    if (isDismissible) {
      onDismiss?.();
    }
    returnFocus();
  }

  function handleOnOpen(): void {
    setPositionY(windowHeight * initialSnapPointFraction);
    if (typeof document !== 'undefined') {
      originalFocusEl = originalFocusEl ?? (document.activeElement as HTMLElement | null);
    }
    /* Defer focus to after first paint so the close button has mounted. */
    requestAnimationFrame(() => {
      requestAnimationFrame(focusOnInitialRef);
    });
  }

  function handleOnClose(): void {
    setPositionY(0, false);
  }

  /* Sync controlled open state to internal animation/position. */
  $effect(() => {
    if (unmountTimeoutId !== null) {
      clearTimeout(unmountTimeoutId);
      unmountTimeoutId = null;
    }
    if (isOpen) {
      isMounted = true;
      /* Defer to next frame so the animation runs on first render. */
      const rafId = requestAnimationFrame(() => {
        isVisible = true;
        handleOnOpen();
      });
      return () => cancelAnimationFrame(rafId);
    }

    isVisible = false;
    handleOnClose();
    if (isMounted) {
      unmountTimeoutId = setTimeout(() => {
        unmountTimeoutId = null;
        if (!isOpen) {
          isMounted = false;
          /* Reset measured heights so re-open replays the entrance animation. */
          headerHeight = 0;
          footerHeight = 0;
          contentHeight = 0;
          grabHandleHeight = 0;
          positionY = 0;
        }
      }, UNMOUNT_FALLBACK_MS);
    }
    return () => {
      if (unmountTimeoutId !== null) {
        clearTimeout(unmountTimeoutId);
        unmountTimeoutId = null;
      }
    };
  });

  /* Stack registration. */
  $effect(() => {
    if (isMounted) {
      addBottomSheetToStack(id);
      return () => removeBottomSheetFromStack(id);
    }
    return undefined;
  });

  /* Body scroll lock — defer to `body-scroll-lock-upgrade` so we get
   * `reserveScrollBarGap: true` (no layout shift on Windows / non-overlay
   * scrollbars) and proper iOS Safari momentum handling. Mirrors React's
   * `useScrollLock({ targetRef: scrollRef, reserveScrollBarGap: true })`. */
  $effect(() => {
    if (!scrollEl) return undefined;
    const target = scrollEl;
    const isReady = contentHeight > 0;
    const shouldLock = isReady && stackArr.length > 0;
    if (shouldLock) {
      disableBodyScroll(target, { reserveScrollBarGap: true });
      return () => enableBodyScroll(target);
    }
    return undefined;
  });

  /* Belt-and-braces: clear all body locks when the last sheet unmounts
   * (matches React's `clearAllBodyScrollLocks()` cleanup). */
  $effect(() => {
    if (stackArr.length === 0 && typeof document !== 'undefined') {
      clearAllBodyScrollLocks();
    }
  });

  /* Track viewport height for snap-point math — use portal target height when
   * portaling into a bounded container (e.g. checkout phone frame). */
  $effect(() => {
    const target = portalTarget;
    if (target) {
      windowHeight = target.clientHeight;
      const observer = new ResizeObserver(() => {
        windowHeight = target.clientHeight;
      });
      observer.observe(target);
      return () => observer.disconnect();
    }
    return undefined;
  });

  onMount(() => {
    if (typeof window === 'undefined') return undefined;
    if (portalTarget) return undefined;
    windowHeight = window.innerHeight;
    const handler = (): void => {
      windowHeight = window.innerHeight;
    };
    window.addEventListener('resize', handler);
    return () => window.removeEventListener('resize', handler);
  });

  /* Measure grab handle height (matches React's effect). */
  $effect(() => {
    if (!grabHandleEl) return;
    void isOpen;
    const cs = getComputedStyle(grabHandleEl);
    const marginBottom = parseFloat(cs.marginBottom) || 0;
    grabHandleHeight = grabHandleEl.getBoundingClientRect().height + marginBottom;
  });

  /* Escape key dismisses the top sheet (when dismissible). */
  $effect(() => {
    if (!isMounted) return undefined;
    function onKeyDown(event: KeyboardEvent): void {
      if (event.key !== 'Escape') return;
      if (!isOnTopOfStack) return;
      if (!isDismissible) return;
      close();
    }
    window.addEventListener('keydown', onKeyDown);
    return () => window.removeEventListener('keydown', onKeyDown);
  });

  /* Prevent body scrolling for over-pull on iOS Safari. Kept as-is — the
   * scroll-lock library handles the page-level overscroll, but this still
   * suppresses the rare sub-pixel negative-scrollTop case on touchstart. */
  $effect(() => {
    if (!scrollEl) return undefined;
    const node = scrollEl;
    function preventOverscroll(event: Event): void {
      if (node.scrollTop < 0) event.preventDefault();
    }
    node.addEventListener('touchstart', preventOverscroll, { passive: false });
    return () => node.removeEventListener('touchstart', preventOverscroll);
  });

  /* Drag handler — verbatim port of React's `useDrag` body
   * (BottomSheet.web.tsx lines 248–368). Receives `isContentDragging` as
   * a positional arg so we can wire two `DragGesture` instances (grab handle
   * vs. content scroll element) instead of using `bind(args)` (which has no
   * vanilla equivalent). */
  /* eslint-disable @typescript-eslint/no-explicit-any */
  function runDragHandler(state: any, isContentDragging: boolean): void {
    const {
      active,
      last,
      cancel,
      tap,
      movement: [, movementY],
      velocity: [, velocityY],
      lastOffset: [, lastOffsetY],
      down,
      dragging,
      event,
    } = state;

    /* Escape hatch — components like SpinWheel can opt out of drag
     * interception via `[data-allow-scroll]`. */
    const touchTarget = event?.target as Element | undefined;
    const isScrollableContent = touchTarget?.closest('[data-allow-scroll]');
    if (isScrollableContent) {
      return;
    }

    isDragging = Boolean(dragging);

    const rawY = lastOffsetY - movementY;
    const lowerSnapPoint = windowHeight * snapPoints[0];
    const upperSnapPoint = windowHeight * snapPoints[snapPoints.length - 1];

    /* Velocity-driven momentum — same formula as React. */
    const predictedDistance = movementY * (velocityY / 2);
    const predictedY = Math.max(
      lowerSnapPoint,
      Math.min(upperSnapPoint, rawY - predictedDistance * 2),
    );

    let newY = rawY;

    if (down) {
      const dampening = 0.55;
      if (totalHeight < upperSnapPoint) {
        newY = rubberbandIfOutOfBounds(rawY, 0, totalHeight, dampening);
      } else {
        newY = rubberbandIfOutOfBounds(rawY, 0, upperSnapPoint, dampening);
      }
    } else {
      newY = predictedY;
    }

    const isPosAtUpperSnapPoint = newY >= upperSnapPoint;

    if (isContentDragging) {
      if (isPosAtUpperSnapPoint) {
        newY = upperSnapPoint;
      }

      /* Pin to upper snap point while content isn't scrolled to top — keeps
       * the scroll feel natural when crossing the boundary between sheet
       * drag and content scroll. */
      const isContentScrolledAtTop = scrollEl != null && scrollEl.scrollTop <= 0;
      if (lastOffsetY === upperSnapPoint && !isContentScrolledAtTop) {
        newY = upperSnapPoint;
      }
      preventScrolling = newY < upperSnapPoint;
    }

    if (last) {
      const [nearest, lower] = computeSnapPointBounds(
        newY,
        snapPoints.map((point) => windowHeight * point) as SnapPoints,
      );

      const lowerPointBuffer = 60;
      const lowerestSnap = Math.min(lower, totalHeight) - lowerPointBuffer;
      const shouldClose = rawY < lowerestSnap;

      if (shouldClose) {
        if (isDismissible) {
          isDragging = false;
          cancel();
          close();
          return;
        }
        isDragging = false;
        cancel();
        const firstSnapPoint = windowHeight * snapPoints[0];
        setPositionY(firstSnapPoint, true);
        return;
      }

      /* `filterTaps: true` makes taps fire with `last: true, tap: true` —
       * skip the snap-to-nearest branch so a tap doesn't trigger a flicker. */
      if (!active && !tap) {
        newY = nearest;
      }
    }

    setPositionY(newY, !down);
  }
  /* eslint-enable @typescript-eslint/no-explicit-any */

  /* Wire `DragGesture` instances reactively. We attach to the same elements
   * React binds: the grab handle (with no `args`, so `isContentDragging` is
   * false) and the body's scroll element (with `isContentDragging: true`).
   * `from` is a getter so each drag-start picks up the *current* `positionY`. */
  $effect(() => {
    if (!grabHandleEl) return undefined;
    if (!isOnTopOfStack || !isOpen) return undefined;
    const gesture = new DragGesture(
      grabHandleEl,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (state: any) => runDragHandler(state, false),
      { from: () => [0, positionY], filterTaps: true },
    );
    return () => {
      /* Reset drag flag so the exit transition isn't suppressed by
       * `transition: none` if `isOpen` flips false mid-drag. */
      isDragging = false;
      gesture.destroy();
    };
  });

  $effect(() => {
    if (!scrollEl) return undefined;
    if (!isOnTopOfStack || !isOpen) return undefined;
    const gesture = new DragGesture(
      scrollEl,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (state: any) => runDragHandler(state, true),
      { from: () => [0, positionY], filterTaps: true },
    );
    return () => {
      isDragging = false;
      gesture.destroy();
    };
  });

  /* Gate touchmove on the body while we're not at the upper snap point —
   * mirrors React's `preventScrollingRef`-driven listener. The `scroll`
   * event is non-cancelable per spec, so only `touchmove` is wired here.
   * `passive: false` is required for `preventDefault()` to actually block
   * the gesture; modern browsers default touchmove on scrollables to
   * passive. */
  $effect(() => {
    if (!scrollEl) return undefined;
    const node = scrollEl;
    function preventScrollingHandler(event: Event): void {
      if (!preventScrolling) return;
      const target = event.target as Element | null;
      const isAllowedComponent = target?.closest('[data-allow-scroll]');
      if (!isAllowedComponent) {
        event.preventDefault();
      }
    }
    node.addEventListener('touchmove', preventScrollingHandler, { passive: false });
    return () => {
      node.removeEventListener('touchmove', preventScrollingHandler);
    };
  });

  /* Provide context to descendants. The getter returns the live state object
   * so updates propagate automatically. */
  const contextValue: BottomSheetContextValue = {
    isInBottomSheet: true,
    get isOpen() {
      return isVisible;
    },
    close,
    get isHeaderFloating() {
      return !hasBodyPadding && isHeaderEmpty;
    },
    get isDismissible() {
      return isDismissible;
    },
    setContentHeight: (h: number) => {
      contentHeight = h;
    },
    setHeaderHeight: (h: number) => {
      headerHeight = h;
    },
    setFooterHeight: (h: number) => {
      footerHeight = h;
    },
    setHasBodyPadding: (has: boolean) => {
      hasBodyPadding = has;
    },
    setIsHeaderEmpty: (empty: boolean) => {
      isHeaderEmpty = empty;
    },
    setScrollElement: (el: HTMLElement | null) => {
      scrollEl = el;
    },
    setDefaultFocusElement: (el: HTMLElement | null) => {
      defaultFocusEl = el;
    },
  };
  setBottomSheetContext(() => contextValue);

  const surfaceStyle = $derived(
    [`--bs-position-y:${positionY}px`, `--bs-z-index:${bottomSheetZIndex}`].join(';'),
  );

  const styledProps = $derived(getStyledPropsClasses(rest));
  const surfaceExtraClasses = $derived((styledProps.classes || []).filter(Boolean).join(' '));

  const grabHandleClasses = $derived(
    [bottomSheetGrabHandleClass, !hasBodyPadding && isHeaderEmpty ? bottomSheetGrabHandleFloatingClass : '']
      .filter(Boolean)
      .join(' '),
  );

  const surfaceMetaAttrs = metaAttribute({
    name: MetaConstants.BottomSheet,
    testID: testID ?? 'bottomsheet-surface',
  });
  const surfaceA11yAttrs = makeAccessible({ modal: true, role: 'dialog' });
  const grabHandleMetaAttrs = metaAttribute({ name: MetaConstants.BottomSheetGrabHandle });
  const analyticsAttrs = $derived(makeAnalyticsAttribute(rest));

  const surfaceState = $derived(isVisible ? 'open' : 'closed');
</script>

{#if isMounted}
  {#if portalTarget}
    <div use:portal={portalTarget} class={bottomSheetPortalRootClass}>
      {@render overlay()}
    </div>
  {:else}
    <div use:portal={document.body}>
      {@render overlay()}
    </div>
  {/if}
{/if}

{#snippet overlay()}
  <BottomSheetBackdrop
    isOpen={isVisible}
    zIndex={bottomSheetZIndex}
    {isDismissible}
    onClose={close}
  />
  <div
    class="{bottomSheetSurfaceClass} {surfaceExtraClasses}"
    style={surfaceStyle}
    data-state={surfaceState}
    data-dragging={isDragging}
    {...surfaceMetaAttrs}
    {...surfaceA11yAttrs}
    {...analyticsAttrs}
  >
    <div class={bottomSheetInnerWrapperClass}>
      <div bind:this={grabHandleEl} class={grabHandleClasses} {...grabHandleMetaAttrs}></div>
      {@render children()}
    </div>
  </div>
{/snippet}
