// packages/blade-svelte/src/components/Input/PhoneNumberInput/CountrySelector.svelte
<script module lang="ts">
  import type { BaseInputSize } from '../BaseInput/types';

  // Flag width in px, mirrors React's `flagSize` (global size tokens 16/16/20/24).
  const flagSize: Record<BaseInputSize, number> = {
    xsmall: 16,
    small: 16,
    medium: 20,
    large: 24,
  };
</script>

<script lang="ts">
  import { getDialCodeByCountryCode, getFlagOfCountry } from '@razorpay/i18nify-js';
  import {
    ActionList,
    ActionListItem,
    ActionListItemAsset,
    ActionListItemText,
  } from '../../ActionList';
  import { BottomSheet, BottomSheetHeader, BottomSheetBody } from '../../BottomSheet';
  import { ChevronDownIcon } from '../../Icons';
  import type { CountrySelectorProps } from './types';

  let {
    isDisabled = false,
    selectedCountry,
    countryData,
    onItemClick,
    flags,
    size,
  }: CountrySelectorProps = $props();

  let isOpen = $state(false);

  const countryNameFormatter = new Intl.DisplayNames(['en'], { type: 'region' });

  const flagSrc = $derived(getFlagOfCountry(selectedCountry)['4X3']);
  const triggerLabel = $derived(`${countryNameFormatter.of(selectedCountry)} - Select Country`);

  const handleSelect = ({ value }: { value: string }): void => {
    onItemClick({ name: value });
    isOpen = false;
  };
</script>

<button
  type="button"
  class="country-selector-trigger"
  disabled={isDisabled || undefined}
  aria-label={triggerLabel}
  aria-haspopup="dialog"
  aria-expanded={isOpen}
  onclick={() => (isOpen = true)}
>
  <img
    loading="lazy"
    role="presentation"
    width={flagSize[size]}
    src={flagSrc}
    alt=""
  />
  <span class="country-selector-chevron">
    <ChevronDownIcon size="small" color="surface.icon.gray.muted" />
  </span>
</button>

<BottomSheet {isOpen} onDismiss={() => (isOpen = false)}>
  <BottomSheetHeader title="Select A Country" />
  <BottomSheetBody hasActionList>
    <ActionList selectedValue={selectedCountry} onItemSelect={handleSelect}>
      {#each countryData as country (country.code)}
        <ActionListItem title={country.name} value={country.code}>
          {#snippet leading()}
            <ActionListItemAsset src={flags[country.code]?.['4X3'] ?? ''} alt={country.name} />
          {/snippet}
          {#snippet trailing()}
            <ActionListItemText>{getDialCodeByCountryCode(country.code)}</ActionListItemText>
          {/snippet}
        </ActionListItem>
      {/each}
    </ActionList>
  </BottomSheetBody>
</BottomSheet>

<style>
  .country-selector-trigger {
    display: inline-flex;
    align-items: center;
    gap: var(--spacing-2);
    padding: 0 var(--spacing-3);
    height: 100%;
    border: none;
    background: transparent;
    cursor: pointer;
    outline: none;
  }

  .country-selector-trigger[disabled] {
    cursor: not-allowed;
    opacity: 0.5;
  }

  .country-selector-trigger:focus-visible {
    box-shadow: 0 0 0 var(--border-width-thick) var(--surface-border-primary-muted);
    border-radius: var(--border-radius-small);
  }

  .country-selector-chevron {
    display: inline-flex;
    align-items: center;
  }
</style>

// packages/blade/src/components/Input/PhoneNumberInput/CountrySelector.tsx
import type { CountryCodeType, getFlagsForAllCountries } from '@razorpay/i18nify-js';
import { getDialCodeByCountryCode, getFlagOfCountry } from '@razorpay/i18nify-js';
import React from 'react';
import {
  ActionList,
  ActionListItem,
  ActionListItemAsset,
  ActionListItemText,
} from '~components/ActionList';
import { BottomSheet, BottomSheetBody, BottomSheetHeader } from '~components/BottomSheet';
import { Box } from '~components/Box';
import type { DropdownOverlayProps } from '~components/Dropdown';
import { Dropdown, DropdownButton, DropdownOverlay } from '~components/Dropdown';
import { ChevronDownIcon, ChevronUpIcon } from '~components/Icons';
import { useIsMobile } from '~utils/useIsMobile';
import { size as sizes } from '~tokens/global';
import { makeSize } from '~utils';

const countryNameFormatter = new Intl.DisplayNames(['en'], { type: 'region' });

type CountryData = {
  code: CountryCodeType;
  name: string;
}[];
type CounterSelectorProps = {
  selectedCountry: CountryCodeType;
  inputWrapperRef: DropdownOverlayProps['referenceRef'];
  countryData: CountryData;
  onItemClick: (props: { name: string }) => void;
  flags: ReturnType<typeof getFlagsForAllCountries>;
  isDisabled?: boolean;
  size: 'medium' | 'large';
};

const CountrySelector = ({
  isDisabled,
  selectedCountry,
  inputWrapperRef,
  countryData,
  onItemClick,
  flags,
  size,
}: CounterSelectorProps): React.ReactElement => {
  const [isDropdownOpen, setIsDropdownOpen] = React.useState(false);
  const isMobile = useIsMobile();

  const actionList = (
    <ActionList>
      {countryData.map((country) => {
        return (
          <ActionListItem
            key={country.code}
            onClick={onItemClick}
            leading={<ActionListItemAsset src={flags[country.code]} alt={country.name} />}
            title={country.name}
            value={country.code}
            trailing={
              <ActionListItemText>{getDialCodeByCountryCode(country.code)}</ActionListItemText>
            }
          />
        );
      })}
    </ActionList>
  );

  const flagSize = {
    medium: makeSize(sizes[20]),
    large: makeSize(sizes[24]),
  } as const;

  return (
    <Dropdown isOpen={isDropdownOpen} onOpenChange={setIsDropdownOpen}>
      <DropdownButton
        isDisabled={isDisabled}
        size={size === 'medium' ? 'xsmall' : 'medium'}
        variant="tertiary"
        accessibilityLabel={`${countryNameFormatter.of(selectedCountry)} - Select Country`}
        icon={() => (
          <Box display="flex" flexDirection="row" gap="spacing.2">
            <img
              loading="lazy"
              role="presentation"
              width={flagSize[size]}
              src={getFlagOfCountry(selectedCountry)}
              alt=""
            />
            {isDropdownOpen ? <ChevronUpIcon /> : <ChevronDownIcon />}
          </Box>
        )}
      />
      {isMobile ? (
        <BottomSheet>
          <BottomSheetHeader title="Sort By" />
          <BottomSheetBody>{actionList}</BottomSheetBody>
        </BottomSheet>
      ) : (
        <DropdownOverlay referenceRef={inputWrapperRef}>{actionList}</DropdownOverlay>
      )}
    </Dropdown>
  );
};

export { CountrySelector, countryNameFormatter };
